### ISSUE TITLE
Allow user to enter p-value cutoff for differentially expressed genes

### ISSUE THREAD

**Issue by alokito** [chanzuckerberg/cellxgene#1004]
Currently the differential analysis is limited to the top 10 genes. It would be nice if the user could input a p-value cutoff, and have it return all the genes below the cutoff. see also #1003

**Comment by alokito** [comment]
see also #1003

**Comment by colinmegill** [comment]
Related to https://github.com/chanzuckerberg/cellxgene/issues/994

**Comment by alokito** [comment]
Related to #95

**Comment by sidneymbell** [comment]
This would indeed be super useful! Unfortunately, though, cellxgene doesn't know anything about the shape of the data coming in. As such, we can't verify if the statistical assumptions are met (e.g., that data is normally distributed), so the differential expression results are exploratory, rather than formal, results. Given this uncertainty, we won't be implementing a p-value threshold at this time.
