### ISSUE TITLE
Spatial feature ideas

### ISSUE THREAD

**Issue by michelgw** [chanzuckerberg/cellxgene#1026]
It's really cool that you can visualize spatial data by adding coordinates in the anndata obsm annotation. Here are a few feature ideas:

* Multi-sample view
Could be really useful to page through samples or layer in one view with adjustable opacity (i.e. serial sections of the same tissue). I imagine this would involve accessing multiple .h5ad files that each have X_spatial

* Background image
Could be great to upload a background image behind the spatial data

* Toggle visualization of clusters
The idea would be to add a contour plot and smooth out regions of clusters

**Comment by bkmartinjr** [comment]
CC: @ambrosejcarr

**Comment by ambrosejcarr** [comment]
Hi Michelle, Thanks for making the issue! I have a few questions to improve my understanding of how these requests help with your research. They're going to sound repetitive. 😅 

1. For multi-sample view: what are you hoping to learn about the data by paging through samples or co-visualizing? What questions can you answer about your data by doing this? 

2. For background images, I can imagine a few reasons you'd want this. Can you walk me through what questions this helps you answer?

**Comment by michelgw** [comment]
Hi @ambrosejcarr, thank you for your response! By co-visualizing, I would hope to investigate differences in cluster patterns or expression across sections from the same tissue (i.e. are we resolving clusters in the physical structures we observe? And if so, how does the clustering compare or contrast in the subsequent layers? Is this reconstruction consistent with what we expect? I think the exploration will bring about many new questions). The immediate utility would be visual control of multiple sections while maintaining their individual analysis annotations, rather than juxtaposition of different windows. Regarding the background images, the questions are similar but relate to our translational focus. I imagine testing views of the spatial data above tissue with different staining (hematoxylin and eosin, immunostaining, etc).

**Comment by liaprins-czi** [comment]
I have heard similar asks from other users recently:

camillee@stanford.edu: Want to view several organ-individual combinations simultaneously
- Individuals as columns, organs as rows, then can scroll
- Important for human and lemur datasets because they are not all clones of each other like mice are, only difference is the mouse’s age
- Still has all the cells just shown once across whole screen

ktrav@stanford.edu: Want to view cells separated by “compartment” and each with their own embedding, simultaneously
- Likes this view a lot to see genes that are compartment-specific
- “Compartment” = level above cell type, hierarchically
- Easier to see which genes are more strongly expressed in which compartment
![compartment](https://user-images.githubusercontent.com/53277128/78607139-5db3d600-7813-11ea-9e7c-2588db610407.png)

**Comment by ambrosejcarr** [comment]
Multi-sample view is supported at present via custom embeddings as @liaprins-czi demonstrates above. Tagging @MaximilianLombardo, as we may wish to create a tutorial that explains how to generate these embeddings. 

Background images are not a priority for the team at this time. 

Contour plot to smooth out regions is related to #1457, and we can continue discussion of this topic there. 

I'm going to close this since there aren't open questions unique to this issue that the team will prioritize in 2021.
