### ISSUE TITLE
erratic undo/redo/reset behavior on "color by" toggling

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1099]
Here is an example of one instance where history is lost and it isn't possible to undo or redo:
![bug1](https://user-images.githubusercontent.com/8716829/72014614-11a5c500-3215-11ea-8699-0b0690c55967.gif)

Here is another example where undoing and redoing do not have an effect on the color state:
![bug2](https://user-images.githubusercontent.com/8716829/72014613-11a5c500-3215-11ea-8361-7304a09361ab.gif)

**Comment by mweiden** [comment]
Small update: you can reproduce the first behavior described by @seve by a simpler set of actions. Try any action from `debounceOnActions`, hit undo, and then perform the same action. This behavior is caused by this logic:

https://github.com/chanzuckerberg/cellxgene/blob/124254d5eda6f970dd3f379450d1bb1c3a37bed3/client/src/reducers/undoableConfig.js#L168-L171
