### ISSUE TITLE
[Heroku] app was successfully deployed but could not be launched

### ISSUE THREAD

**Issue by mxiang128** [chanzuckerberg/cellxgene#1146]
Hi,

I tried to host my dataset on Heroku for data sharing. I provided a link to a small test dataset for testing. It showed that the app is successfully deployed but it could not be launched:

Error: Unable to open file (file signature not found) - file not found or is inaccessible.  File must be an .h5ad object.  Please check your input and try again.

I was able to launch this dataset locally. Link to data: https://stanfordmedicine.box.com/s/oqt9qzzuwesc8wk5wsodh7ca3fmsk3pr

Your help is appreciated!

Menglan

**Comment by seve** [comment]
Hi @mxiang128 - thanks for creating an issue!

Just so I understand your issue a little better:
* Are you are using the [one-click Heroku button](https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fchanzuckerberg%2Fcellxgene%2Ftree%2Fmaster%2Fexperiments%2Fheroku&template=https%3A%2F%2Fgithub.com%2Fchanzuckerberg%2Fcellxgene%2Ftree%2Fheroku) to host cellxgene?
* If so are you using the link you provided(https://stanfordmedicine.box.com/s/oqt9qzzuwesc8wk5wsodh7ca3fmsk3pr) as the DATASET config var?
  * If so, you are seeing that error because the dataset is behind a box portal which cannot be traversed by Heroku
  * In order for a Heroku deployment of cellxgene to work properly, the dataset must be hosted on a publicly accessable url. [Read here in the section titled "When should I not deploy with Heroku?" for more information.](https://chanzuckerberg.github.io/cellxgene/posts/hosted)

**Comment by mxiang128** [comment]
Thanks for your prompt response @seve! Yes to all your questions. I actually made the Box link accessible by the public. I tried with Google Drive and Dropbox links and both failed, which I suspect it's due to the same reason? Is there an alternative way to upload my data then? Sorry for all the naive questions!

**Comment by seve** [comment]
No worries! You may be correct that the Drive and Dropbox links are not working for the same reasons.

In order for the Heroku setup to work properly, it has to be given a link that downloads a dataset without any interaction further than navigating to the link.  
For example, if you navigate to the default link in the Heroku setup (https://raw.githubusercontent.com/chanzuckerberg/cellxgene/master/example-dataset/pbmc3k.h5ad). The file is instantly downloaded without any further interaction.

I plan on integrating the existing feature to use s3:// and gs:// URLs in the future, but as of now they are not supported on the provided Heroku config.

**Comment by mxiang128** [comment]
Thanks for the explanation! I modified the google drive link according to [this post](https://stackoverflow.com/a/45652982/3255218) I found that allows generating a publicly accessible URL. Now if you click on it the download automatically starts: https://drive.google.com/uc?export=download&id=1Tt2zznCf_LIgGhF79goGr3S7eIlFs-v6.   However Heroku still gives the same error... Would you happen to know why?

**Comment by seve** [comment]
@mxiang128 Looks like a bug to me! 

If I utilize the ability to launch cellxgene from a URL this should alleviate the problem. I've assigned this to myself and as this is unlinked from deployment, I will not tag a release.

**Comment by seve** [comment]
@mxiang128 The fix is now live :+1:

**Comment by mxiang128** [comment]
@seve Great! I have hence learned to use the Stanford Digital Repository to host my h5ad file and create a permanent url, but this is still a nice feature to have.

**Comment by seve** [comment]
Fixed in #1196
