### ISSUE TITLE
subset UI refinement

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1192]
There are a number of behaviors in the current subset UI that need refinement . Collecting them here, and they are subject to change at the moment.

1. "reset the subset" feature should not clear other UI state.  Currently the "reset the subset" feature clears other UI state.  It should not clear anything other than the data subset.  For example, it currently clears the color-by mode.  Some of this will be tricky to unwind, so creating a tracking issue.

2. Subset should clear selection state, as by definition the result of the subset matches the previous selection.

3. ...

**Comment by liaprins-czi** [comment]
I've thought about some basic "rules" we can have to guide what to do upon subset and undo-subset, for various states. Here's what I've come up with:
- If the state, when set by the user, was dependent upon the cell-type population (i.e. clipping), then clear upon both subset and undo-subset, as subset and undo-subset change inherently change that cell population.
- If the state itself affects/changes the selected cell population (i.e. label and histogram selections), then clear upon subset, since by definition subset accounts for just the cells remaining in the selections anyhow (and it’s not necessarily useful to show selections that already reflect the entire population).
- If the state is not affected by population (i.e. color-by, user-added genes), maintain it across both subset and undo-subset.

Based on those, I made a table that reflects what should happen in the UI for each of those states when either subset or undo-subset.

However, I'm interested to hear others thoughts, @bkmartinjr @colinmegill especially for `DE selection(s) (pre-run)`, `clipping`, and `lasso showing`, as there might be other usecases or I might be over-estimating the usecases I provide in the table.

![Screen Shot 2020-04-28 at 9 31 35 AM](https://user-images.githubusercontent.com/53277128/80513505-ff6ea480-8933-11ea-84eb-42abc8961620.png)

**Comment by bkmartinjr** [comment]
After discussions with @colinmegill, we are implementing this proposal with a few modifications:
1. all selections (graph, continuous, categorical) will reset to "all" when a subset operation is done.
2. clipping will be unaffected by subset/unsubset, as clipping does not affect, nor is it affected by, the subsetting of cells
3. diffexp changes are deferred until the upcoming diffexp rework.

The remainder of the changes (eg, color-by) will be done as described above.
