### ISSUE TITLE
integrate cxgtool into cellxgene CLI

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1341]
the stand-alone tool should get integrated as another cellxgene sub-command

**Comment by tihuan** [comment]
Not sure the definition of done is clearly defined, so can't estimate!

Questions:
1. What's the standalone tool we want to integrate?
2. What's the expected behaviors from the user's perspective when this issue is done? How many new subcommands can they execute now?
3. Any breaking changes to the existing commands?

**Comment by maniarathi** [comment]
This ticket involves moving the code in `cxgtool.py` into another `cellxgene` CLI sub-command. As part of this migration, the conversion functions translating from H5AD files to CXG files will be modularized and broken out into utility functions. In addition robust unit testing will be added to unit test each sub-component of the conversion process. Finally, documentation will be added so that users will be able to use the tool if they would like to (though the primary use case today is internally).

1. The standalone tool is the command line tool to convert from H5AD to CXG.
2. There should be no user's perspective changed; if anything, @mckinsel will need to be briefed on any changes.
3. No breaking changes.

**Comment by bmccandless** [comment]
@maniarathi There is also the "to_sparse.py" tool that converts a dense cxg dataset to a sparse cxg dataset.   I'm not sure we need to integrate into the cxgtool, but that script should continue to work.

**Comment by maniarathi** [comment]
👍  I wasn't planning on modifying that one as part of this work. Will continue to leave as is.

**Comment by bmccandless** [comment]
to_sparse depends on cxgtool.py

**Comment by tihuan** [comment]
@maniarathi and @mckinsel will collaborate on this!

**Comment by maniarathi** [comment]
This was closed on accident.. #1739 was a partial solution.
