### ISSUE TITLE
All labels visible when only one annotation is selected?

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/cellxgene#1444]
I was playing with free annotations with this [dataset](https://cellxgene.cziscience.com/d/krasnow_lab_human_lung_cell_atlas_10x-1.cxg/)

Why are all the labels displayed when I've only selected one?

<img width="1162" alt="Screen Shot 2020-05-01 at 4 12 00 PM" src="https://user-images.githubusercontent.com/3644743/80848049-b7b37b80-8bc6-11ea-9af1-5441482f9be7.png">

I'm trying to understand the intended scenario.

**Comment by bkmartinjr** [comment]
I think the idea of highlighting the selected, or omitting the unselected, is a great idea....

**Comment by colinmegill** [comment]
Making the labels responsive to the checkboxes is a solid idea @brianraymor, and would make the interface feel more reactive. I agree this would be in line with user expectations.

An option since we don't remove cells on checkbox toggle:

Cells (present interaction): 
   1. Deselect checkmark 
   2. De-emphasize by reducing size

Labels (proposal): 
   1. Deselect checkmark
   2. De-emphasize by *reducing opacity* while maintaining legibility

Here's what that would look like in action: 

![image](https://user-images.githubusercontent.com/1770265/80920624-ff5d1300-8d3e-11ea-816a-c5768588eb76.png)

This keeps the pattern consistent across cells and labels (they appear, disappear, get bigger/bolder together). This also preserves our ability to *emphasize* labels on left sidebar hover that were de-emphasized by being unchecked. In action, presently:

![image](https://user-images.githubusercontent.com/1770265/80920643-1c91e180-8d3f-11ea-9d27-0683a7a4d02b.png)
_deselected, but hovered, and thus emphasized_

I'm generally opposed to emphasizing selected labels that aren't hovered. This would mean losing emphasis on hover, and would mean all labels were bold if one checkbox is deselected. Important selection state:

![image](https://user-images.githubusercontent.com/1770265/80920511-57dfe080-8d3e-11ea-83b9-9bf6a2c68c2e.png)
