### ISSUE TITLE
Share my results

### ISSUE THREAD

**Issue by fenghuijian** [chanzuckerberg/cellxgene#1445]
How can I share my results with others?
How can someone else access my local IP address or LAN IP address to see my results？

**Comment by ambrosejcarr** [comment]
Hi @fenghuijian apologies for missing this question! If it is still relevant for you, we have documentation on how to [share your cellxgene results with others over the internet](https://chanzuckerberg.github.io/cellxgene/posts/hosted). 

I'm going to close this issue because of its age, but if this answer doesn't address your question please open another issue and we'd be happy to discuss further.
