### ISSUE TITLE
Gene expression not shown in gene's histogram after subset (not all genes, though)

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1497]
Found when testing with https://cellxgene.dev.single-cell.czi.technology/d/WongAdultRetina.cxg/

I had added the gene KCNQ1, then subset to 12,117 cells by lassoing (will be difficult for others to to reproduce due to this). Then the following phenomena resulted:
-  KCNQ1's min number on its x-axis became a very long-digited negative decimal, so long it does not fit in the space provided under the x-axis. Its max number became also a negative decimal.
- I could not select anything on the histogram; there were no bars shown: none of the cells remaining after subset have any KCNQ1 expression I think. However, KCNQ1 should still include “0” as part of its x-axis and then show the tall bar there (if all cells have 0-level of expression).
- The scatterplot shows nothing when that gene is chosen for one of the axes.
- Furthermore, when I color by that gene, it colors everything purple, but the color scale legend is black.

Because lasso-subsetting created this bug, it will be difficult to reproduce. So I hit "undo" bunch until the point at which I subset, then made a video of me hitting "redo" a bunch to show the sequence of events. Giphy made the resolution to small to see the numbers, **so I made a video instead: https://drive.google.com/open?id=1kFXpmuru2XnWVa-O8jAwMgUqL2XtcdjP**

Here are screenshots:

_The long x-axis tick number_
![Screen Shot 2020-05-27 at 9 27 49 AM](https://user-images.githubusercontent.com/53277128/83051236-8f227400-a002-11ea-9d53-2d3bd97ee94b.png)

_The Console message + scatterplot without any dots_
![Screen Shot 2020-05-27 at 9 31 19 AM](https://user-images.githubusercontent.com/53277128/83051242-947fbe80-a002-11ea-8dd3-ee8f481ffb59.png)

_The inspector to see what the long digited decimal was trying to show_
![Screen Shot 2020-05-27 at 9 32 19 AM](https://user-images.githubusercontent.com/53277128/83051256-9a759f80-a002-11ea-85ff-dd7338df8aad.png)

_Coloring by KCNQ1 strangely makes all dots purple, and the legend black!_
![Screen Shot 2020-05-27 at 9 33 54 AM](https://user-images.githubusercontent.com/53277128/83051266-9e092680-a002-11ea-94f4-478cbe083bae.png)

Mysterious!

**Comment by bkmartinjr** [comment]
Root cause: all selected cells have exactly the same value for the annotation in question (in this case, the expression value for KCNQ1).  If you perform more or less the same selection of cells, you see roughly the same behavior on other annotations, such as `pct_counts_in_top_500_genes`: 

![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/242a08b3-b967-4c79-829a-63dd5f6d1a1c)

When all cells have the same value, the code in `brushableHistogram` component does not correctly fall back to something suitable for a single-bin dataset.  For example, `calcHistogramCache`, contains code that is confused if bin width is zero (ie, min & max values are equal).

The min and max values are available from the dataframe `summarize()` function.  For example, `calcHistogramCache()` accesses them like this:

```
    const summary = col.summarize();
    const { min: domainMin, max: domainMax } = summary;
```
