### ISSUE TITLE
WSGI version demo/docs on how to use with plain OAUTH

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1522]

**Comment by tihuan** [comment]
What's the definition of done?

Questions:
1. What does `demo` mean here? Is it an example repo that sets up WSGI cellxgene with plain OAuth, so the users can see how to integrate OAuth? Do we need to host the example solution for them to play with?

2. Where should the docs live? [Here](https://github.com/chanzuckerberg/cellxgene/tree/main/dev_docs)?

3. From a user's perspective, what should they be able to achieve after this issue is done? Will they have a step-by-step guide on how to set up OAuth, or is it just high level summary and tips?

**Comment by Bento007** [comment]
This issue is too open ended and needs concrete goals. This issue could be anywhere from a 2-8 depending on what the outcome is expected to be.

**Comment by bmccandless** [comment]
For this issue, I intend to document how the feature works and document the configuration parameters.
For the "demo" part I think that providing a link to the czi hosted cellxgene site is sufficient
There is already a README (https://github.com/chanzuckerberg/cellxgene/blob/main/server/eb/README.md)  file that documents everything you need to do to setup your own hosted cellxgene site.
I'll add a section to that document.
This is a pretty small issue.

**Comment by bmccandless** [comment]
We should improve our secret handling before documenting oauth.
It could be made easier to use (and document) with this issue done:

chanzuckerberg/cellxgene#1859
