### ISSUE TITLE
Rerun the CXG conversion on all H5AD files

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#1800]
cc @mckinsel 

--Why--
The CXG format was developed pretty iteratively and the current datasets in cellxgene all conform to different versions of the CXG format. Some of the modifications to the CXG format over time were not recorded so even if two datasets show that they are on the same version of CXG, they actually might differ in structure. In the long run, this can cause data anomalies, incompatibilities, and will make migrations complicated in case we make changes to the CXG format in a way that is not backwards compatible. 

In order to prevent these future issues, we should re-run the CXG conversion tool on all existing H5AD datasets and deploy them.

-- Definition of Done --
- [ ] CXG tool is run on each dataset available in dev/staging/prod. This means that each CXG should have a version number tagged on and it should be the same.
- [ ] If the conversion was not clean, a new ticket should be created per broken dataset (or potentially per error bucket if datasets failed for similar reasons).
- [ ] A small diff script should be written to verify that the old and new CXG datasets are similar/different in the expected ways (i.e. content similar, not corrupted, but version is different).
- [ ] The new CXGs should replace the existing ones in the respective buckets. Gotcha here: DO NOT REPLACE the cxg directory. You must delete and then re-add the CXG with the same name. A simple replacement will lead to corruption.
- [ ] Verify that each dataset that was converted displays correctly in cellxgene. This will need to be done in dev, staging, and prod.

**Comment by bmccandless** [comment]
Also consider changing the sparse threshold value (15 percent seems to be a good number).  Most of the current matrices can be made sparse.

I'd also caution that reconverting the datasets using then new cxgtool may lead to anomalies.   The old older datasets where all made with older and different versions of the cxgtool, and with different versions for tiledb, it's possible that the new conversion tool does not capture the behavior of all the previous versions.  (example, say a code change was made long ago to work around something unique in dataset A, but later that work around was refactored such that it no longer handles the special case in A)

I think this needs to be done with some care, so we don't break published datasets.  We should take time to check each dataset first.  Instead of immediately replacing existing datasets, I suggest first making a new version so we can check it side by side with the original.    

Perhaps also write a scripts to compare two datasets with respect to all the arrays, types, and values, to make sure we can spot and understand any differences between the old and new datasets.

**Comment by tihuan** [comment]
@bmccandless 's idea SGTM! And I'll estimate with that in mind 😄

**Comment by signechambers1** [comment]
Closing since this is outdated and schema 2.0 work will require re-curating.
