### ISSUE TITLE
Create a new sandbox deployment of cellxgene

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/cellxgene#1867]
Need: in order to avoid collisions with testing new features on the dev deployment of cellxgene, we'd like to spin up one more sandbox "dev" deployment available for testing.

Definition of Done:
- [ ] Work with Infra to spin up the sandbox deployment of dev.
- [ ] Set up the regular deployment of the sandbox based on the answer to the below open question.

Open questions:
- [ ] What should be the deployment cycle of the sandbox? Nightly deployment of `main` to the sandbox? Same as `dev` that gets updated after each PR to main?

**Comment by tihuan** [comment]
Ooh I was imagining the new sandbox environments will be used on demand instead of having a regular deployment cycle. Say, anytime an engineer wants to test certain code from any branch, they can just deploy their commit to one of the sandboxes whenever they want, and notify people in ops channel they're using which sandbox, so we don't have sandbox collision.

And for Nightly, it sounds similar to daily staging deployment, but I'm trying to think if there's any difference in benefits of having both nightly and daily staging deployment, and just daily staging deployment!

**Comment by maniarathi** [comment]
Closing this ticket since the work being done by Central Infra via Happy Path will enable this.
