### ISSUE TITLE
Annotation PUT call needs to stop retrying at certain point

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/cellxgene#1981]
Context:
Currently FE keeps retrying a failed annotation PUT request **indefinitely**, but we need to stop retrying at some point, otherwise it will be DDOS on our servers

What:

1. Retry 3 times with exponential backoff (pick a reasonable cool down initial value please! Like 5 seconds or something)

1. Note that after retrying three times, we'll stop retrying. But if the user makes another annotation change, it should send another request + 3 retries too. This means that we'll need a mechanism to manage retry vs. new request. E.g., while retrying, a new annotation change comes in, then we should abort the current retry and start a new request + retry cycle

**Comment by tihuan** [comment]
@maniarathi @signechambers1 PTAL! Not sure when we wanna pull this in, but just wanted to let you know the ticket is here lol Thank you!

**Comment by seve** [comment]
Closing this issue as a "will not fix".

* Because the FE tick only PUTs when user anno updates or the previous PUT fails this isn't a major load, unless the backend is unhealthy in which we make the attempt at every tick.  In the case that the backend **is** unhealthy, this is just an attempt at resolving backend bugs with a frontend fix.

* Adding a constant exp. backoff will lead to FE clients getting in sync via the load balancer which would only compound the issue.

* Holding off PUT's for too long increases the chance of having the unwanted state of sitting on unsaved user edits, increasing the chance that we lose that data

* Our system and user size won't cause these retries to expand into DDOS territory

* The proposed solution in #2001 introduces race conditions where out of date in-flight PUT's may be handled after more recent edits. Corrupting and overriding recent user edits.
