### ISSUE TITLE
[FEATURE REQUEST]The starting umap is colored, not black

### ISSUE THREAD

**Issue by longfeili5170** [chanzuckerberg/cellxgene#2025]
Hello.

I want the initial UMAP image to be colored instead of black. When I open cellxgene. Because I found that the initial black UMAP image gives a bad feeling. 
Is it possible to modify a certain source code or achieve this goal in other ways?

Thanks

**Comment by colinmegill** [comment]
Hi @longfeili5170 — we've discussed allowing scientists to add a default color by as a parameter when booting, but if my memory is correct this is not implemented. We decided against picking a random colorby. 

If you're comfortable modifying the source code and want to do this on your deployment, it is, in fact, a simple feature to hack in.

You will need to add this line:

```
    dispatch({
      type: "color by categorical metadata",
      colorAccessor: "subtissue",
    });
```

in the `componentDidMount` method of `client/src/components/app.js`. `subtissue` should be replaced with your categorical or continuous field of preference. A reasonable place to do that is after the initial data bootstrap line: 

`dispatch(actions.doInitialDataLoad(window.location.search));`

**Comment by longfeili5170** [comment]
Thank you for such a quick reply @colinmegill 
But I can’t find app.js, I installed cellxgene0.16.6 through conda. And cellxgene source code does not exist in miniconda3/envs/cellxgene/lib/python3.7/site-packages.
Here are all the packages:
<img width="1097" alt="屏幕快照 2021-01-20 上午10 45 44" src="https://user-images.githubusercontent.com/68364890/105120248-dcf96880-5b0c-11eb-9630-1191577ebed2.png">

**Comment by colinmegill** [comment]
@longfeili5170 if you want to hack on the repo, I think you'll need to clone it from this repository to your local environment using git, not pip.

**Comment by colinmegill** [comment]
See: https://github.com/chanzuckerberg/cellxgene/tree/main/dev_docs

**Comment by longfeili5170** [comment]
It works.
Thank you very much!!

**Comment by RamiyaSiva** [comment]
Hi, 

I was wondering if there are any updates on this feature request. I would like to do the same thing, preferably without having to modify the source code. 

Thank you!

**Comment by MaximilianLombardo** [comment]
Hey @RamiyaSiva to my knowledge this is not implemented in the current release of CELLxGENE

@longfeili5170 would you be able to share a fork of the information that ended up working for you?

**Comment by MissingNuit** [comment]
@colinmegill

**Comment by MaximilianLombardo** [comment]
@MissingNuit

generally speaking,  the CELLxGENE team is not currently able to guarantee guidance/support w.r.t. customization/new implementations of the CELLxGENE Explorer. That being said, in order to foster more of a discussion for any other community members who may want to join in, you may want to consider adding additional context to your issue. As a starting point, you could consider adding the following:

1. what is the error message that you are receiving when trying to launch the dataset with your modified source code?
2. are you launching with a dataset that you've downloaded from the portal/can you provide access to a sample version of the dataset?
3. version of CELLxGENE explorer that you have modified

If you are using a dataset downloaded form the portal, have you tried specified the default categorical variable to color by as 'cell_type'? That is how the field is defined in the [CELLxGENE schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.1.0/schema.md)
