### ISSUE TITLE
The server situation required to deploy  cellxgene[QUESTION]

### ISSUE THREAD

**Issue by longfeili5170** [chanzuckerberg/cellxgene#2031]
Hello!
I plan to deploy cellxgene to the server, but I don't know the required server situation. 
For example, when I plan to deploy 5 data sets of 100k cells, what is the server situation I need, such as running memory?

Thanks！

**Comment by MaximilianLombardo** [comment]
Hey @longfeili5170,

Thanks for using cellxgene and for submitting your question!

W.r.t. memory usage - A good rule of thumb would be to have the memory on your server roughly equal or greater (erring towards greater) than the size of your uncompressed `.h5ad` object since the object is loaded into memory on your server. Once extra consideration you may have, is that if your are running 5 simultaneous instances of cellxgene with each of your 5 datasets, you'll likely need server memory >= the sum of the uncompressed file sizes.

Max

**Comment by longfeili5170** [comment]
Thank you for your reply.
But I still have some questions.
1.I store the file through csc_matrix to make it a sparse matrix and the h5ad_file storage memory will be small. If I don’t use csc_matrix, the memory will expand tenfold.Which storage memory should I refer to?

2.I am very worried about multiple people visiting at the same time.How many server audits should I choose to deal with this situation ？

**Comment by MaximilianLombardo** [comment]
Hey,

1.) You can refer to the size of the `.h5ad` with a sparse expression matrix. I think the `csc_matrix` is fine - but I think that anndata defaults to using a `csr_matrix` [https://anndata.readthedocs.io/en/latest/anndata.read_h5ad.html](url) - so you may want to abide by that convention. For some extra fun - here is some reading by one of the ScanPy/AnnData creators on sparse formats [http://www.falexwolf.de/blog/171212_sparse_matrices_with_h5py/](url) 

Additionally, if you are worried about conserving memory, you can launch cellxgene with the `--backed` option, but this will result in a slower ability to access expression values

2.) On the subject of server audits - By audit, do you mean monitoring? In that case you can use whatever the standard monitoring tools are and check for HTTP latency and memory shortages (eg, paging rate). Please consider that the system is not designed for high scale multi-user use, so in scenarios where you are expecting >10s of users, then you may need to pursue a solution where you bring up multiple replicas and put behind a load balancer.
