### ISSUE TITLE
[BUG] calculating the logFC

### ISSUE THREAD

**Issue by FADHLyemen** [chanzuckerberg/cellxgene#2207]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Desktop or hosted?:
 - Browser (if hosted) [e.g. chrome, safari]:
 - Version [e.g. 0.13.0]:

**Additional context**

In the code:
https://github.com/chanzuckerberg/cellxgene/blob/f36d88945542920bbb0ea93312707f0702b9ffe1/backend/server/compute/diffexp_generic.py

They calculated the logFC
 logfoldchanges = np.log2(np.abs((meanA + 1e-9) / (meanB + 1e-9)))

I think they should use only meanA -meanB if it is not count values.

**Comment by FADHLyemen** [comment]
I am getting different logFC than Seurat using FindMarkers function
https://www.rdocumentation.org/packages/Seurat/versions/4.0.1/topics/FindMarkers

**Comment by FADHLyemen** [comment]
https://github.com/satijalab/seurat/blob/96d07d80bc4b6513b93e9c10d8a9d57ae7016f9f/R/differential_expression.R#L176-L178

**Comment by MaximilianLombardo** [comment]
Hey Fadhl, 

A conversation around this issue was also started by another user. In order to consolidate, let's have the conversation (including updates) in [this issue thread](https://github.com/chanzuckerberg/cellxgene/issues/2211) and close this issue thread for now.

FYI, the temporary solution is that we are not reporting these metrics (p-value and log fold change) but still listing the differentially expressed genes. Can you let us know in the other thread if this affects your workflow?
