### ISSUE TITLE
Incorrect differential expression with log-transformed data [BUG]

### ISSUE THREAD

**Issue by JohnnyOmics** [chanzuckerberg/cellxgene#2211]
It appears that the differential expression (as log fold-change) calculation in `diffexp_ttest()` and `diffexp_ttest_from_mean_var()` assumes raw count data as input and will produce incorrect values if the expression data is log-transformed. The relevant code (in the latter function) is...
(line 67)   `logfoldchanges = np.log2(np.abs((meanA + 1e-9) / (meanB + 1e-9)))`
but for log-transformed expression data should be simply
`logfoldchanges = meanA - meanB`
For count data, the abs() call would be unnecessary unless counts can be negative. Also note that while the existing code would be appropriate for count-based expression, the accompanying use of t-tests to estimate _p_ values is not (since it assumes a normal distribution).
As calculated, the _sign_ of the differential expression will be correct, but not its magnitude. Also, the result is not monotonic with respect to the correct `meanA-meanB`, which means that rankings by log(FC) will also be incorrect.
Unless I'm mistaken and overlooking something this should be considered a high-priority fix!

**Comment by MaximilianLombardo** [comment]
Hey Johnny,

Yes, I think you are right. In the cases where data are already logged, the current implementation will not yield the correct result. I guess the issue lies with dividing the means of the already logged values - as this results in something like a base change right?

I think that the abs value was maybe used to deal with the scenario when doing the computation on the already data (because additional normalization/scaling was likely applied, i.e. z-score transformation resulting in negative values in the expression matrix). 

I think that [ln(ln(x))](https://www.google.com/search?q=ln%28ln%28x%29%29&ei=3VakYIbpHcb2gQaXt4WoBg&oq=ln%28ln%28x%29%29&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEJECMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAOgcIABBHELADOgQIABAeOgYIABAIEB46BggAEAoQHlC5-wNYy4gEYJWLBGgBcAJ4AIABjQGIAZ8FkgEDMC41mAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwjGy9TzudTwAhVGe8AKHZdbAWUQ4dUDCA4&uact=5) is still monotonically increasing (i.e. order preserving).

The issue around the normal assumption not being valid is definitely true and we are aware of it. We have decided to make this assumption to simplify the computation and gain speed in delivering the results of the differential expression.

I think that genes and rank that are delivered are based on the test statistic and that the log fold change is simply used for reporting purposes (but that this incorrect nonetheless).

Is this an accurate description of what is going on?

**Comment by JohnnyOmics** [comment]
Hi Max,

Thanks for the quick response!

Yes, the main issue is that `log(meanA/meanB)` is for count data and won't give correct values when `meanA` and `meanB` are already log-transformed (which may usually be the case, since the **prepare** program does that, I think). And while `log(log x)` is monotonic where it is defined, `log(log(x)/log(y))` is not, compared to the proper `log(x)-log(y)`.

For example, in log space, let meanA = 3 and meanB = 2, so that the log fold-change is meanA - meanB = 1. Then the existing code will give  log2(3/2) = **0.585**. Now let meanA = 8 and meanB = 6 for a logFC of 2. But now we get log2(8/6) = **0.415** for the 2X higher fold change.

It's not a difficult fix; a one-liner, in fact, if you know whether your data is linear (counts) or log domain. If not, then testing for values over 20 or so is pretty reliable, since you're not likely to see 2^20 (1048576) counts of anything!

**Comment by MaximilianLombardo** [comment]
Sounds great, Johnny. I'll circle back with the team on this - stay tuned!

**Comment by MaximilianLombardo** [comment]
Hey Johnny,

Quick update, we are temporarily removing the display of these metrics (log fold change and p-value), but the differential expression feature and list of top 10 genes will still remain intact. In the meantime, we are deciding whether to fix or permanently remove the display of these metrics. Please let us know if this would impact your workflow with cellxgene or any other suggestions you might have!

**Comment by FADHLyemen** [comment]
I do not know how removing p-value or logFC will fix it.

**Comment by MaximilianLombardo** [comment]
Hey Fadhl,

It wouldn't necessarily be a fix. Perhaps the more appropriate term to describe this situation would be a "resolution". Our current understanding is that while the log-fold change calculation is incorrect under certain scenarios (when the data is already logged), the genes displayed are still statistically significant markers (that are ranked appropriately) and are valid for exploring the data. Therefore, to still serve the use case of exploring the data, we felt that a valid solution would be to remove the metrics which are misleading (a.k.a. incorrect under certain circumstances) while keeping that top 10 list of differentially expressed genes to help users identify distinguishing features of the population of interest.

When making these decisions, we prioritize our user's needs and the use case that we are trying serve ("exploration"). In this particular scenario, our team has the notion that our users generally aren't making a lot of use of these particular metrics. The flip side is that while some potential fixes have been suggested in this thread, there are still some complications with implementation (i.e. for "desktop cellxgene explorer" we don't know the logged status of the data in advance and would have to rely on heuristics which wouldn't necessarily work under all circumstances). Additionally, a fix might need to be different between our desktop version of cellxgene explorer and the [hosted cellxgene explorer](https://cellxgene.cziscience.com/), so we also need to take into account engineering bandwidth since we are working on some other features that we perceive to be higher priority.

All that being said, we are striving to make this decision in an open way. We welcome any feedback on the intended path forward in this thread or in the [following slack thread](https://cziscience.slack.com/archives/CCTA8DF1T/p1622067239002700). Thus far, we haven't received a strong opinion form the community regarding our intended resolution, but would love to have more information on how you use these features in your single cell exploration workflow!

**Comment by JohnnyOmics** [comment]
We found that the p values were reasonable and the signs (directions) of fold change were preserved, even if the magnitudes are way off. So it seems reasonable to rank genes by p value without reporting FC until a "permanent" fix can be implemented. If you know that these are log-space expression numbers (but watch out for log2() vs. ln(), as Seurat reports) the simple fix above will work, but I don't think we've heard the last word about differential expression in single-cell RNASeq and you probably want to avoid too many abrupt changes in the way this is done.
If you decide to use a count-space method like DESeq2 for DE, then you'll want to use the p values it generates instead of the t-test p values as is done currently.

**Comment by MaximilianLombardo** [comment]
Thanks for this feedback Johnny, this makes sense and is useful information for us to decide on a "permanent" fix. I think a potential compromise might be to remove the metrics (or even retain reported p-values), but still report the directionality of the fold change (i.e. whether it was up or down regulated in the population of interest). Please let the team know if you think having the magnitude reported would be particularly beneficial in this scenario.

**Comment by JohnnyOmics** [comment]
Well, you're right that this a data visualization/exploration tool (and a good one!) and not an analysis platform, but there may be people who use it in the latter way.
One more note though... The way that p values are determined (t-tests) is appropriate for log-transformed values because they can be assumed to be roughly normally distributed. That's not the case for count data, though. This is actually what tripped me off here: the p value and logFC calculations were making opposite assumptions about the data.
Answering your question... Again this is a data visualization platform, but my guess is that users who are interested in the DE will be asking why they can't see the metrics!

**Comment by MaximilianLombardo** [comment]
Yes, those are certainly relevant points. When making this decision, the team knew that the statistical assumptions didn't necessarily hold for count data as you have mentioned (although maybe as single cell datasets get larger, [the central limit theorem](https://en.wikipedia.org/wiki/Central_limit_theorem) will save us - half kidding). The feature was originally implemented to give a quick and dirty (my words, not the cellxgene team's) list of reasonable markers without making guarantees about statistical accuracy - we try to be open about this decision and the limitations (although this aspect might be better described) in our [documentation](https://chanzuckerberg.github.io/cellxgene/posts/methods).

I agree, there will be some users who might miss the feature and we encourage them to speak out. That being said we try to make decisions based on the greatest amount of value that will be derived by the greatest number of users and try to help those users whose use cases are not met by our implementations find workarounds within reason :)

Thanks for contributing to this discussion in a productive way!

**Comment by bkmartinjr** [comment]
@JohnnyOmics - in case you want to review, see #2318
