### ISSUE TITLE
Does hosting cellxgene on the web allow for downloading of the data?

### ISSUE THREAD

**Issue by LisaSikkema** [chanzuckerberg/cellxgene#2237]
Hi!

I would like to give my collaborators access to *viewing* a dataset of mine, by hosting cellxgene on the web. However, I do not want to share the full count matrices yet. I was therefore wondering: is it possible for my collaborators to download the data if they have the link to my web cellxgene instance? Or does cellxgene not allow such downloads (which would be perfect for us in this case)?

Thanks!

Lisa

**Comment by MaximilianLombardo** [comment]
Hey Lisa!

Thanks for the question! If you are self-hosting (as opposed to using [hosted cellxgene](https://cellxgene.cziscience.com/)), then your users should not be able to download the data using the cellxgene interface. To play it safe, when you create your AnnData object - you could could omit the raw counts layer, but maintain the normalized expression matrix. This allows for visualization, but guarantees that people will not have access to the count matrix since it wouldn't even be hosted.

**Comment by LisaSikkema** [comment]
Thanks for the quick response! Okay that's good to know.
I think in theory the adata.X layer would still allow to reconstruct the raw counts right? Just by undoing the log-transformation and normalisation.
But either way we're self-hosting, so it should be okay!

**Comment by MaximilianLombardo** [comment]
I guess it depends on the normalization/pre-processing that you use in your pipeline and which version of the raw count matrix you want to "protect". If it is simply log normalized, then I agree it would trivial to reconstruct the count matrix. If you have done anything such as regression based on mitochondrial fraction, background removal, or even cell size normalization, then I think it would be challenging for someone to recreate the original raw count matrix - although, I haven't tried it before :)
