### ISSUE TITLE
Can cell type related parameters be merged and organized ...

### ISSUE THREAD

**Issue by Shixuan1** [chanzuckerberg/cellxgene#2267]
**Describe the bug**
For large dataset, the cell type list can be very long and hard to get to the cells of interest. 
The cells are ordered alphabetically by name but some cells may be named differently by different people and thus added the complexity to find the cells.
The cell ontology and cell type are related, but right now the selections are separated. I hope all the cell type related parameters (e.g., cell ontology, cell type names, compartment) can be merged and organized in a hierarchical manner with pull-down menus. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Desktop or hosted?:
 - Browser (if hosted) [e.g. chrome, safari]:
 - Version [e.g. 0.13.0]:

**Additional context**

**Comment by brianraymor** [comment]
>The cells are ordered alphabetically by name but some cells may be named differently by different people and thus added the complexity to find the cells.

Once we finish dataset re-curation for [schema 2.0.0](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md), all datasets in the **cellxgene explorer** on the [portal](https://cellxgene.cziscience.com/) will observe the CL ontology for cell types and all human-readable labels will be standard and applied by the portal. 

Redundant ontology information will be removed from the left side bar when the enclosing epic is completed. 

I may open a new issue to focus on the remaining request because we have some early designs under consideration for this case:

> For large dataset, the cell type list can be very long and hard to get to the cells of interest.

**Comment by brianraymor** [comment]
Tracking the remaining suggestion in [Improve finding values in large categories in the cellxgene explorer LSB](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/240). Closing this issue.
