### ISSUE TITLE
gene highlights 

### ISSUE THREAD

**Issue by terooatt** [chanzuckerberg/cellxgene#2303]
Thank you for this very nice tool!

One feature of cellxgene is that you can highlight the cells based on the expression of a gene by just clicking on the gene barplot, but somehow now I am unable to use this feature anymore. By doing some troubleshooting I seem to loose this feature after I perform a size factor normalization using scran as shown below and I can't seem able to figure out what is the problem.  

#Normalize adata 
adata.X /= adata.obs['size_factors'].values[:,None]

#after normalizing with an external tool I resparsified the matrix as it follows:
import scipy as scipy
adata.X = scipy.sparse.csr_matrix(adata.X)

**Comment by MaximilianLombardo** [comment]
Hey there - thanks for this question and for using cellxgene!

Would you be able to provide some further context on the version of cellxgene/python you are using?

Also, w.r.t. to the size factor normalization - this still produces a matrix with numeric values right? (i.e. doens't populate the matrix with None and NaN values?)

**Comment by Jon-bioinfo** [comment]
Hi, colleague of the original poster here.

This issue seems to be related to how the .X matrix is encoded. Using the demo data at https://cellxgene-example-data.czi.technology/pbmc3k.h5ad if I run

```
import scanpy as sc
import numpy as np
import scipy
adata = sc.read('pbmc3k.h5ad')
adata.X = scipy.sparse.csr_matrix(adata.X, dtype=np.float32)
adata.write('pbmc3k_32.h5ad')

adata = sc.read('pbmc3k.h5ad')
adata.X = scipy.sparse.csr_matrix(adata.X, dtype=np.float64)
adata.write('pbmc3k_64.h5ad')
```

Then the highlighting of cells by selecting a region of the gene expression histogram only works for pbmc3k_32.h5ad in cellxgene v0.17.0

This is also a problem because h5ad files produced by [SeuratDisk](https://mojaveazure.github.io/seurat-disk/) seem to use float.64

Which is probably also the cause of https://github.com/chanzuckerberg/cellxgene/issues/2291 since the Azimuth data h5ad file was likely produced with SeuratDisk and looks like:
```
adata = sc.read('local.h5ad')
adata.X
<982538x77521 sparse matrix of type '<class 'numpy.float64'>'
	with 1748651019 stored elements in Compressed Sparse Row format>
```

**Comment by terooatt** [comment]
Thank you all of you. Parsing all my AnnData from float 32 to float 64 did the job. I am closing the issue now.
