### ISSUE TITLE
Slow completion for CLI commands

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2470]
Seve noticed cellxgene --version took a few seconds to complete, Emanuele noted that cellxgene-schema also has a slow response time. 

This ticket should invesitgate: how widespread is the slowness for CLI commands? Can we speed up these response times? 

Hosted is a higher priority than desktop, however if it is negligible to also fix for desktop that may be worth doing if the fix reduces maintenance burden or code complexity as well.

Potentially helpful: https://www.tomrochette.com/problems/2020/03/07

**Comment by blrnw3** [comment]
cellxgene-schema:
This was taking ~5s to get a response to the help command. By inlining some imports I was able to take this down to 0.1s

cellxgene / single-cell-explorer:
Response is in the 1-2s range.
Unfortunately the imports cannot be easily inlined because most of them are needed in order to generate the options for the CLI (they are dependent on yaml files rather than being statically defined in code).
I tried inlining the heaviest imports such as pandas but the import stack is rather wide and deep so the dependency would just pop back up somewhere else.
My recommendation for now is to leave cellxgene CLI as is. Fixing the responsiveness would require a substantial refactor and would result in messier code IMO.

Attached is a profile of single-cell-explorer imports
![Screen Shot 2021-12-22 at 2.37.31 PM.png](https://images.zenhubusercontent.com/610982edf31b482dd14d578a/f0fbcf32-340d-407b-9241-270d53154070)
and after some inlining showing no progress:
![Screen Shot 2021-12-22 at 2.39.11 PM.png](https://images.zenhubusercontent.com/610982edf31b482dd14d578a/da498924-cb75-45c6-a71f-0b30255eb115)

**Comment by atolopko-czi** [comment]
@signechambers1 @brianraymor Should we call this done or do we want to put any additional effort into it? Ben's report, above, shows there is not much we can easily do and recommends leaving as is. (A small improvement for `cellxgene-schema --help` performance is now in place).

**Comment by brianraymor** [comment]
I have a separate issue for [Profile cellxgene-schema CLI](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/163), so I'm fine closing this one.

**Comment by atolopko-czi** [comment]
@signechambers1 I'm going to optimistically close this out. Feel free to re-open if you want override.
