### ISSUE TITLE
[QUESTION] Ensembl gene name

### ISSUE THREAD

**Issue by Edhelia** [chanzuckerberg/cellxgene#2606]
Hi :)

I had asked a question here, but for Cellxgene_VIP. 

My question is also about Cellxgene. I have an h5ad file that I downloaded from the cellxgene database. When I explore this file directly from the site, there is no problem I can enter my genes of interest by their name (eg STAT5). However, as soon as I launch the file from my conda environment, it is impossible to enter the names of the genes, I have to enter the Ensembl numbers (ENSG......). I can't understand why. 

I did the test with other h5ad files and I have the same problem.

Can you help me?

Thanks in advance :)

PS: excuse my English :p
![Capture d’écran du 2023-04-20 10-52-26](https://user-images.githubusercontent.com/123067144/233313515-b5a4fd26-2584-4d61-99d3-88e3e69d8e26.png)

**Comment by MaximilianLombardo** [comment]
Hi @Edhelia - you can use the `--var-names` flag when using `cellxgene launch` to specify a column in the `var` dataframe to have CELLxGENE explorer search for features there instead of the default location, the index of that dataframe.

For datasets downloaded from the portal that would be `feature_name`

Ex:

`cellxgene launch myDataset.h5ad --var-names feature_name`

**Comment by Edhelia** [comment]
It works perfectly :) Thanks a lot :)
