### ISSUE TITLE
404 Error when running differential test on cellxGene

### ISSUE THREAD

**Issue by bijuissacch224610** [chanzuckerberg/cellxgene#2613]
I am getting a usual 404 error from cellxGene for a particular dataset. I have not seen this error in any other datasets I created before or after this one dataset. (see attachment). The dataset has 155308 cells. The error appears even if I select very few cells into each group for comparison. My question is whether cellxGene has any limitations on how many genes can be tested using this function?

Thanks
-Biju
<img width="1168" alt="Screen Shot 2023-05-05 at 8 09 57 AM" src="https://user-images.githubusercontent.com/83024487/236454294-ab5df451-cbb6-4e43-9ee8-69685bc88335.png">
<img width="1164" alt="Screen Shot 2023-05-05 at 8 08 54 AM" src="https://user-images.githubusercontent.com/83024487/236454309-16236942-c1c5-4aab-bfe5-9de0eb959fa8.png">

**Comment by MaximilianLombardo** [comment]
Hi @bijuissacch224610 

Thanks for the question. A few clarifying questions:

1. What version of CELLxGENE are you running?
2. How many features are in your dataset?
3. When you run the function and run into the error, can you check the terminal/command line and report the stack trace back here?

**Comment by bijuissacch224610** [comment]
Hi @MaximilianLombardo 

Thanks for the help. Here are my replies

1. What version of CELLxGENE are you running? 
	I am currently using a self-host cellxgene version v1.1.0
2. How many features are in your dataset? 
	Our dataset currently has 21207 features in 155308 cells in 2 conditions
3. When you run the function and run into the error, can you check the terminal/command line and report the stack trace back here? 
	Can you guide me on how to get this traceback from terminal/server, since we use the self host cellxgene and we do not obtain error traceback on the browser? If you can guide me, I can try and obtain the same

Thanks
-B

**Comment by MaximilianLombardo** [comment]
Hey @bijuissacch224610 - thank you for the additional context!

> I am currently using a self-host cellxgene version v1.1.0

My first suggestion would be to upgrade your version of CELLxGENE to v1.1.2. I'm not sure that your issue is related to it, but we fixed an issue related to some of CELLxGENE's underlying dependecies in that version (see this [issue](https://github.com/chanzuckerberg/cellxgene/issues/2608) for details).

> Our dataset currently has 21207 features in 155308 cells in 2 conditions

The size/dimensionality of your dataset should not be causing the issue - that is well within CELLxGENE's capabilities.

> Can you guide me on how to get this traceback from terminal/server, since we use the self host cellxgene and we do not obtain error traceback on the browser? If you can guide me, I can try and obtain the same

Sure! I think the first thing to do would be to install CELLxGENE locally and see if the dataset is still giving you any issues - you can follow the directions for installing CELLxGENE locally [here](https://cellxgene.cziscience.com/docs/05__Annotate%20and%20Analyze%20Your%20Data/5_1__Getting%20Started:%20Install,%20Launch,%20Quick%20Start). We recommend installing CELLxGENE inside a fresh [conda](https://docs.conda.io/en/latest/) environment.

After that, try launching your dataset with CELLxGENE locally `cellxgene launch mydataset.h5ad`. Once the dataset has been launched, you can go to your browser and paste the link that is displayed in your terminal (it should look like this `http://localhost:5005`). From there you can run your differential expression and IF you encounter the error again, you can refer back to your terminal to see the traceback. This process would help identify if the dataset is the problem. Otherwise you may need to consult with whoever set up your self-hosted CELLxGENE as the error may be specific to your self-hosting configuration.



Let me know if any of the install

**Comment by bijuissacch224610** [comment]
Thank you for all the help. We traced down the fault to low RAM availability on the server for the cellxGene. The error disappeared when we increased RAM

**Comment by MaximilianLombardo** [comment]
Fantastic - thanks for letting us know!
