### ISSUE TITLE
[QUESTION] Upload multiple datasets (.h5ad)

### ISSUE THREAD

**Issue by vschnei** [chanzuckerberg/cellxgene#2614]
Hi everyone,
I am about to setup a cellxgene server for our published single cell datasets. 
Deployment of cellxgene via docker worked perfectly fine for me. Though I couldn't find any option to upload multiple datasets from different projects.

Is there any way to do that? In my case this would be a really nice feature.

Thank you!

**Comment by vschnei** [comment]
Just read in the roadmap. 
`Annotate and persist integrated datasets`
`Once a user integrates multiple datasets, they can create cell labels and gene sets. The integrated dataset, cell labels, and gene sets will be downloadable, and will persist the next time they log in` 
Seems like this feature will be implemented at some point.

**Comment by MaximilianLombardo** [comment]
Hey @vschnei thanks for the question - w.r.t. your first comment, you may want to check out the [cellxgene gateway](https://github.com/Novartis/cellxgene-gateway) projected (developed by a team at Novartis, not maintained by CZI) - it is an extension of CELLxGENE that allows you to use the CELLxGENE with multiple datasets. We unfortunately do not provide user support for self-hosting due to the large number of setups and use cases that we would need to cover.

W.r.t. to your second comment, this actually an outdated roadmap (on an outdated version of our docs site). You can find the current version of our docs [here](https://cellxgene.cziscience.com/docs/01__CellxGene)!
