### ISSUE TITLE
Annotate - update BE dependencies

### ISSUE THREAD

**Issue by dsadgat** [chanzuckerberg/cellxgene#2618]
https://github.com/chanzuckerberg/cellxgene/pulls

- [ ]  Update and pin BE dependencies
- [ ]  Deploy and sanity check that nothing is broken
- [ ]  Update how-to-upgrade-dependencies.md

**Comment by atarashansky** [comment]
This is a noop - the requirements.txt file is already set to pull the latest package versions. Unit tests pass when running them in a fresh installation with the latest versions: https://github.com/chanzuckerberg/cellxgene/pull/2634.

**Comment by atarashansky** [comment]
It appears that a FE plugin called `obsolete-webpack-plugin` is interfering with the GHA testrunner (see failing tests on https://github.com/chanzuckerberg/cellxgene/pull/2634).

Assuming that the issue is due to out-of-date FE dependencies, then this ticket is blocked by the one to upgrade FE annotate deps.

**Comment by joyceyan** [comment]
@dsadgat Just as an FYI, `cellxgene` as it currently is does not appear to work on my M2 machine. A fresh install of main's `requirements-dev.txt` on my machine on a clean virtual environment does not work. This will probably end up taking me a bit longer than someone without an M1/M2 machine, since I'll have to first figure out how to get my local environment set up to run cellxgene as it is (if possible) before I can start updating the backend dependencies.

**Comment by dsadgat** [comment]
@atarashansky I believe you have annotate working? Could you take this one over and pin the Werkzeug dependency via https://czi-sci.slack.com/archives/C0247APK621/p1699544094837979
