### ISSUE TITLE
UX request: keyboard shortcut to switch between pan/zoom and select modes in graph

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#317]
The current graph layout has two modes:   pan/zoom and lasso-select.  Switching between the two requires clicking a button.

It would be VERY convenient if the UI allowed the user to switch between the modes by pressing a key on the keyboard (eg, shift, control, alt, whatever).

**Comment by liaprins-czi** [comment]
Documenting ideas for general keyboard interactions that could apply to this usecase, while I have them in my mind:

- Default mode is that dragging pans (hold down a key/combo to instead enable lasso-ing when drag); scrolling could always zoom
- Inverse of the above: default mode is instead that dragging lassos (hold key/combo button to instead pan upon mouse drag); scrolling could always zoom
- Same as the above ones but zoom could be attached to one of the modes: when that mode is enabled scrolling = zooming; when that mode is _not_ selected nothing happens when scroll (currently zoom is attached to the pan upon drag mode (as opposed to the lasso upon drag mode)
- Press key/combo to zoom the screen in increments; scrolling always scrolls the viz (we might need horizontal (and vertical) scroll bars); dragging always pans
- Press key/combo to zoom the screen in increments; keep UI buttons to toggle between pan upon drag mode versus lasso upon drag mode
- Press key/combo to toggle between current modes (pan upon drag + zoom upon scroll versus lasso upon drag + do nothing upon scroll)
- Press a certain key/combo to go into a certain mode, regardless of current mode; therefore we'd need two keys/combo, one for each mode

**Comment by liaprins-czi** [comment]
See also #1331

**Comment by signechambers1** [comment]
Closing as not a priority
