### ISSUE TITLE
Warning when launching

### ISSUE THREAD

**Issue by fionagriffin** [chanzuckerberg/cellxgene#419]
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

**Comment by neuromusic** [comment]
is this fixed?

**Comment by bkmartinjr** [comment]
Not enough information in the bug report to know if it is fixed or not, as it most likely depends on either the environment or the test dataset.

@fionagriffin - if you have details on how to reproduce this, could you add them to the report?  
If not, but you can reproduce it on your own PC, one of us can pair to diagnose.   Otherwise, we should close it.
