### ISSUE TITLE
Update cellxgene prepare to translate gencode identifier to gene symbol

### ISSUE THREAD

**Issue by fionagriffin** [chanzuckerberg/cellxgene#486]
User story: The data coming out of the HCA expression matrix service is indexed on the gencode identifier (i.e. ENSG00000115263.14). We would like to create a dictionary (can exist as a `.csv`) that contains the translation of gencode identifiers to the gene symbol (GCG) that appends the gene symbol to the matrix. This function should exist as a part of `cellxgene --prepare`. The user should then be able to point to this column during `cellxgene --launch` as described in issue #485.

**Comment by csweaver** [comment]
@fionagriffin I'm not sure I understand. We want to add a translate feature for gencode-> gcg to prepare, is that right? How would this look in the CLI?

**Comment by GenevieveHaliburton** [comment]
@csweaver I was thinking this would look something like `cellxgene --prepare --hca-ids` (or another name for that flag). I imagine this would really just look like `adata = adata.append(genenames)`.

**Comment by csweaver** [comment]
Is there a database that we can query? I'm hesitant to include a static file that contains the maps -- depending on updates that could be a pain to maintain.

Also, is this just an HCA problem? Would other sources provide the gencode identifier as the gene name? (I'm thinking about the flag name)

**Comment by GenevieveHaliburton** [comment]
There are databases that would include all parts of the gencode id that are ahead of the decimal (i.e. ENSG00000115263), which is sufficient to assign to a gene symbol. The matrix service then goes a step further with decimals to a specific (isoform? transcript?) i.e., ENSG00000115263.14. 
Many people use gencode ids so might be better to do something like `--gencode` but I'm not sure if HCA matrix users would know that they're working with gencode IDs. This is something we could def address with documentation. 
One thing to note, in all of these cases I've encountered gencode IDs that don't map back to gene symbols so that will be an issue.

**Comment by GenevieveHaliburton** [comment]
@mckinsel What database or source does the matrix service use to determine gene IDs?

**Comment by neuromusic** [comment]
e.g. mygene.info, you can get "symbol" field from ensembl id or http://mygene.info

**Comment by signechambers1** [comment]
Closing as low priority
