### ISSUE TITLE
Categorical metadata that have only one value should not be selectable

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#572]
If there is a categorical metadata variable that has only one value (e.g. "method" in tabula muris), then we should hide it.

![image](https://user-images.githubusercontent.com/1245615/52020234-67baa600-24a5-11e9-9804-3ad361e6d58d.png)

**Comment by bkmartinjr** [comment]
@colinmegill - thoughts on whether this should be UI layer decision (ie, in component), or suppress at a lower layer (data model)?   I am reasonably sure the former is the right call, as I bet the UI does not want to suppress, but present in an alternative form (ie, show the metadata, but make it non-selectable).

**Comment by colinmegill** [comment]
I do believe we want to display categorical metadata with one option differently - in effect it's information about the entire dataset.

These cases should probably be removed from `categoricalSelectionState` object before it's passed to the more specific components:

```
        >
          Categorical Metadata
        </p>
        {_.map(categoricalSelectionState, (catState, catName) => (
          <Category key={catName} metadataField={catName} />
        ))}
```

Ie., I don't think this should be done in `categorical/categorical.js` because that re-renders frequently. Given that, perhaps we just do it on the backend? 

Re: display, perhaps:

![image](https://user-images.githubusercontent.com/1770265/53842229-e30feb80-3f6c-11e9-8f4d-8d9288bb33b2.png)

**Comment by bkmartinjr** [comment]
I feel pretty strongly it should not be done on the back-end -- we want to make display oriented decisions in the front end.

We could do this as part of the code that summarizes the dataset and decides what to present.  I still think it is a "view" decision (not a model decision), so best done in the component.  If you are worried about performance, just memoize it.

I'm happy to propose something concrete - just assign the bug to me.

**Comment by neuromusic** [comment]
confession: I'm feeling less convinced that this is a bug. it's an accurate representation of the data. are users going to be confused if it isn't there? how should we handle it when we subset and one of the categories suddenly has only one value in it... does that category disappear, only to reappear on a reset?

I'm starting to think that the current behavior minimizes surprise for the user, which is a good thing even if not and efficient data:ink ratio

@sidneymbell do you have any thoughts here?

**Comment by colinmegill** [comment]
Agree with the above and propose we close this / resume if users ask for it.
