### ISSUE TITLE
Gene search typeahead issue

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#573]
Losing focus (maybe?) causes input box to hide the inputted text. Expected behavior -> If I type "ABC" in the input box and then I click on the scatterplot I still expect to see ABC written in the box. Instead, placeholder text is shown.

**Comment by colinmegill** [comment]
The desired behavior is supposed to be the default behavior. It's the result of a single flag, `resetOnClose`. I didn't set it initially because it defaults to `false`, but explicitly setting it to false didn't help. I've filed an issue here and await response.

https://github.com/palantir/blueprint/issues/3483

**Comment by bkmartinjr** [comment]
fixed by #714
