### ISSUE TITLE
Color by 'depth' / 'overlap' of cells in graph to show density of areas

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#597]
For larger datasets of 100,000+ cells, it will be useful to see how many cells are in a given area of the graph. A button on the top right could color by point density to surface that information. 

Thanks to @dpeerlab for the suggestion

**Comment by ambrosejcarr** [comment]
A common implementation approach to this problem is to do a 2-dimensional kernel density estimate of the point cloud. The density estimate can be stored as a value in [0, 1], and these values can be fed directly to the colormap. To get a clean plot in a python implementation, one would need to order the plotting sorted from 0 --> 1 or vice versa. This can produce a bias equal to the radius of the spot, unless opacity is considered.

**Comment by gokceneraslan** [comment]
We've added this as a densityplot to the latest release of scanpy, have a look:  https://icb-scanpy.readthedocs-hosted.com/en/latest/api/scanpy.pl.embedding_density.html#scanpy.pl.embedding_density

**Comment by signechambers1** [comment]
Closing in favor of [#1457](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1457), this contains implementation details
