### ISSUE TITLE
ScanPy API update needed

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#619]
At some point we need to update to the latest ScanPy, and update our usage of the API.  For example, we import `scanpy.api`, which is now deprecated in favor of importing the top-level module.

**Comment by neuromusic** [comment]
This seems to be closely related to the issues with which genes are found in `.X` vs `.raw`.

I think that updating scanpy (for `cellxgene prepare` in particular) will fix #542 as well.

**Comment by bkmartinjr** [comment]
@neuromusic - how would this resolve #542?    I understood that as requiring the ability to pick .raw vs .X, which is a concept the app currently does not imagine....   Or am I misunderstanding the other issue?

**Comment by neuromusic** [comment]
As we drilled down to the core issue in #542, it turned out that the old scanpy drops genes when it creates X and the user was looking for genes that were no longer in X (but were in raw).

My understanding is that if the h5ad file is processed using the latest scanpy, all of the genes will remain in X and therefore available for coloring, bulk add, differential expression, etc.

So rather than supporting access to raw, simply updating scanpy should address the user need here.

**Comment by bkmartinjr** [comment]
Ah, so it is a change affecting `prepare`, not `launch`....  TY

**Comment by sidneymbell** [comment]
I can take this one for `prepare`.

**Comment by sidneymbell** [comment]
Goes hand-in-hand with the update I'm working on for reading alternate filetypes in `launch`.

**Comment by csweaver** [comment]
This should be done. There is further discussion for how to support getting genes from raw vs. .X but I think this issue can be closed
