### ISSUE TITLE
Support alternate file formats for `launch`

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#635]
Anndata supports reading of several different file types. Most of these are raw counts (and already accepted by `prepare`). It would be useful to accept `launch` input of processed data (already normalized, embedded, and annotated) in other formats.

[`loom`](https://linnarssonlab.org/loompy/) files seem like a good first step (basically a structured version of `hdf5`). 
Currently, `loom` is supported for `read/write` by [the dev version of seurat](https://satijalab.org/loomR/loomR_tutorial.html) and the [super new](https://master.bioconductor.org/packages/devel/bioc/vignettes/LoomExperiment/inst/doc/LoomExperiment.html) `SingleCellLoomExperiment` class in bioconductor. 

While this isn't super smooth export for R yet, it's currently (to my knowledge) the only file format that's interoperable between scanpy, seurat and bioconductor. It seems to be gaining traction in both of the major R communities, and I think it would be a good first step (thanks so much to Angela Pisco for her super helpful perspective here!). Notably, because `loom` is structured and `anndata` can read it, this should handle all of the field matching and be pretty quick to implement.

**Comment by sidneymbell** [comment]
Update: `loom` files carry layers of raw and normalized values with them. They also handle metadata quite nicely. However, they currently do not support a slot to hold embeddings (i.e., `obsm` fields). The scanpy team is aware of this: 
https://github.com/theislab/anndata/blob/master/anndata/readwrite/write.py#L81

**Comment by sidneymbell** [comment]
From a super helpful conversation with @falexwolf

>The problem is that loom files don’t support multi-dimensional annotations (I haven’t checked in a while, though). Hence, there is no canonical way of storing coordinates of embeddings.

>What you’d need to do, is presumably, pass a parameter `x-coord` and `y-coord` from the command line interface, which looks up the coordinates from `.obs`; this is where people not using Scanpy typically put them in  `loom` files (in `loom` files, the corresponding attribute is called `.col` and is a dictionary of annotations with length `#observations`).

So, this could be done, but is unlikely to be super helpful as of now given that these coordinates are not being exported by default by any of the major packages.

**Comment by neuromusic** [comment]
The loom documentation indicates that the format *does* support multidimensional column attributes:

> Attributes can be any of the following:
> - One-dimensional arrays of integers, floats or strings. The number of elements in the array must match the corresponding matrix dimension.
> - Multidimensional arrays of any of the same element types. The length along the first dimension of a row attribute must equal the number of rows in the main matrix (and vice versa for column attributes). Remaining dimensions can be any size.

http://linnarssonlab.org/loompy/apiwalkthrough/index.html#row-and-column-attributes

The loom docs there explicitly show PCA, UMAP, tSNE, stored as both multidimensional attributes `ds.ca["TSNE", "PCA", "UMAP"]` and as single-dimensional attributes `ds.ca["PCA1", "PCA2"]`

So while loom has not enforced a schema with the same strictness as anndata, it seems likely that this is where loom users would store this kind of metadata and we could support this with @falexwolf's suggestion of additional parameters that specify where to look for continuous metadata that should be used for the layout.

I'd love to hear @jxtx's thoughts here, as he has explicitly asked for loom support, since that is what the Galaxy team is looking at as a standard file format.

**Comment by sidneymbell** [comment]
Nice, thanks @neuromusic! I think this is upstream from us: IMO, we can support loom files once scanpy `write_loom` supports embeddings. Perhaps open an issue in the scanpy repo with your findings? :)

**Comment by falexwolf** [comment]
Hey everyone! We just went through the process of doing this: https://github.com/theislab/anndata/pull/127

As mentioned, I had thought that loom doesn't even allow multi-dimensional annotations and I'm sure that I got an error when I tried writing them in the early versions of the `write_loom` function. But this seems to have changed. :)

Anyway, we just merged it.

However, I still have the impression that people using loom files tend to store coordinates in two fields `TSNE_1` and `TSNE_2`, for example, rather than using multi-dimensional annotations. But I also don't think that this is a fixed convention.

**Comment by neuromusic** [comment]
thanks @falexwolf! that's fantastic.

and yes, that seems to be a common way to store them: http://linnarssonlab.org/osmFISH/availability/

In lieu of a fixed schema or clear conventions in the loom community, we're still at the same place with needing to support loom users here with additional loom-specific cli arguments that point to where we should extract embeddings from.

I'm inclined to keep this kind of munging out of `cellxgene launch` and instead add a "pass-though" mode to `cellxgene prepare`, which already supports loading from loom files with scanpy's `read_loom`. This "pass-through" mode would skip umap/tsne and instead let the user indicate where in the loom file these embeddings are already stored, then save them out to an h5ad file from which `cellxgene launch` can discover the available embeddings based on scanpy conventions (`obsm['X_<name>']`).

This might even be worth adding to scanpy's `read_loom` function... an `obsm_keys` argument? It could get complicated, though... Using the osmFISH example above, we'd need to support 'X' and 'Y' getting merged into something like `obsm['X_spatial']` and '_tSNE_1' and '_tSNE_2' into `obsm['X_tsne']`.

```
read_loom(
    ...,
    obsm_names=[
        {'X_tsne': ['_tSNE_1','_tSNE_2']}, 
        {'X_spatial': ['X','Y']}, 
    ]
)
```

something like that? that's going to be ugly to specify as a command line argument :/

**Comment by jxtx** [comment]
I thought I had seen some ambiguity in the LOOM docs about whether attributes could be multidimensional. @falexwolf is probably correct that this changed. Changed for the better! We would definitely use this in Galaxy. I'd prefer not to have to prepare duplicate h5ad files (which we would do in a container and then throw away) but if needed we can.

**Comment by neuromusic** [comment]
relevant: https://github.com/theislab/anndata/pull/132

**Comment by neuromusic** [comment]
issue & PR created on anndata repo: https://github.com/theislab/anndata/issues/131

**Comment by neuromusic** [comment]
https://github.com/theislab/anndata/pull/132 has been merged into master on anndata

**Comment by signechambers1** [comment]
Self publication will support datasets in AnnData, Loom, or Seurat v3RDS. Some of this work might allow users to run cellxgene launch on these datasets. From @ambrosejcarr "There's likely a short term "documentation solution" where we say "run convert --> run launch" More sophisticated approaches are a bit hairy because the formats actually have really different performance characteristics; a Seurat RDS object may not support interactive speed calculations because of the way it's laid out."

**Comment by brianraymor** [comment]
@ambrosejcarr to extract information and create new documentation issue for Max. Closing per triage.
