### ISSUE TITLE
Save browser state

### ISSUE THREAD

**Issue by batson** [chanzuckerberg/cellxgene#658]
While investigating a group of cells, I added a bunch of genes, computed some DE (and later, might have annotated some cells). Would be cool to save that state so I can start from there instead of spending 10 min finding my list, adding them, etc.

**Comment by bkmartinjr** [comment]
@batson - can you elaborate on what state you find valuable, and in what format it would be convenient to receive it?

**Comment by batson** [comment]
My ideal would be the ability to click a 'save' button in the browser and shutdown my laptop. then when i restart cellxgene, I can load that and it's as if I never left.

In terms of features, I guess this would be the list of genes I have added, diff exp computed, and potentially selections (histogram, zoom, etc).

**Comment by bkmartinjr** [comment]
I assume "auto save" would be equivalently good? Or do you want manual "save" only?

**Comment by batson** [comment]
"auto save" would be better :-)

**Comment by mollenkt** [comment]
This might be a distinct issue, but it was suggested I add this here:

The Allen Institute would like to launch users from our tools into a particular cellxgene dataset with pre-selected parameters (this is akin to a saved state, hence why I'm posting here.)

As an example, let's say a user is reviewing the info we have about the Sst_Chodl cell type in primary motor cortex in the human. We'd love to provide them a hyperlink into the cellxgene instance hosting the Allen Institute's Human M1 dataset, and when the page loads the coloring of the umap would be pre-set to "final_cross_species_cluster" and only the cells in "human_Sst Chodl" would be selected.

**Comment by signechambers1** [comment]
See related ask in a jupyter notebook form on [#603 ]

**Comment by brianraymor** [comment]
@ambrosejcarr recommends closing during PM triage.

**Comment by heimannch** [comment]
I contacted the team in the Slack channel, and it was recommended that I add my use case for launching cellxgene with pre-selected parameters.

The project that I work on (https://cri-iatlas.org/) is interested in using data from the Human Tumor Atlas Network, which is available for [download and for visualization in cellxgene](https://data.humantumoratlas.org/explore?selectedFilters=%5B%7B%22value%22%3A%22hdf5%22%2C%22label%22%3A%22hdf5%22%2C%22group%22%3A%22FileFormat%22%2C%22count%22%3A11%2C%22isSelected%22%3Afalse%7D%2C%7B%22group%22%3A%22AtlasName%22%2C%22value%22%3A%22HTAN+MSK%22%7D%5D&tab=file). 

We will add visualizations that are specific for the scope of our analyses, and we are interested in providing users a way to easily transition from our platform to explore the data in cellxgene, maintaining the settings defined on our end. In previous integrations, an URL was the solution employed. Ideally the URL would be dynamically generated, based on user selection on our platform, but a static URL with some default setting that we define beforehand would also be very helpful.

**Comment by scheuerm** [comment]
Has this been addressed yet.  I have the same question about saving the configuration state.  Took a fair amount of effort to add marker gene sets for each cell type and would like to retain these without having to reload them.

**Comment by sofroniewn** [comment]
+1 to this request and to #558 - I created some gene sets and saved some selections for differential expression and would like to share them with someone else who wants to look at them too. Having a url with deep linking would be great. A tool that does this very well is neuroglancer, where [this link](https://h01-dot-neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B3.3e-8%2C%22m%22%5D%7D%2C%22position%22:%5B386218.5%2C139541.671875%2C534.5%5D%2C%22crossSectionScale%22:1.4635777089090045%2C%22crossSectionDepth%22:-113.36185634656202%2C%22projectionOrientation%22:%5B-0.9000449180603027%2C0.4170641005039215%2C0.10201209038496017%2C0.07463380694389343%5D%2C%22projectionScale%22:1014.4021429937955%2C%22projectionDepth%22:-93.64863571737415%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://h01-release/data/20210601/4nm_raw%22%2C%22tab%22:%22source%22%2C%22name%22:%224nm%20EM%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%7B%22url%22:%22precomputed://gs://h01-release/data/20210601/c3%22%2C%22subsources%22:%7B%22default%22:true%2C%22bounds%22:true%2C%22properties%22:true%2C%22mesh%22:true%7D%2C%22enableDefaultSubsources%22:false%7D%2C%22tab%22:%22rendering%22%2C%22selectedAlpha%22:0.43%2C%22meshRenderScale%22:0.2076583032715262%2C%22segments%22:%5B%2212370157418%22%2C%2212399227779%22%2C%223504883666%22%2C%223518943222%22%2C%223533881074%22%5D%2C%22segmentQuery%22:%223504883666%2C%203518943222%2C%2012370157418%22%2C%22colorSeed%22:1825171976%2C%22segmentColors%22:%7B%223504883666%22:%22#6666ff%22%2C%223518943222%22:%22#ff6666%22%2C%2212370157418%22:%22#6666ff%22%7D%2C%22name%22:%22c3%20segmentation%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://h01-release/data/20210601/c3/synapses/incoming_excitatory%22%2C%22tab%22:%22source%22%2C%22linkedSegmentationGroup%22:%22c3%20segmentation%22%2C%22linkedSegmentationColorGroup%22:false%2C%22colorSeed%22:2899852909%2C%22segmentDefaultColor%22:%22#ffff00%22%2C%22name%22:%22incoming%20excitatory%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://h01-release/data/20210601/c3/synapses/incoming_inhibitory%22%2C%22tab%22:%22source%22%2C%22linkedSegmentationGroup%22:%22c3%20segmentation%22%2C%22linkedSegmentationColorGroup%22:false%2C%22colorSeed%22:4144453914%2C%22segmentDefaultColor%22:%22#0000ff%22%2C%22name%22:%22incoming%20inhibitory%22%2C%22visible%22:false%7D%5D%2C%22showDefaultAnnotations%22:false%2C%22showSlices%22:false%2C%22prefetch%22:false%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22c3%20segmentation%22%7D%2C%22layout%22:%7B%22type%22:%22xy-3d%22%2C%22orthographicProjection%22:true%7D%7D) will take you to exactly the part of the image that I want you to see with the annotations that I have selected. The same functionality for cellXgene would be great!!

**Comment by MaximilianLombardo** [comment]
Hey all - just following up on some of the more recent comments on this thread

@scheuerm w.r.t. your comment:

> Has this been addressed yet. I have the same question about saving the configuration state. Took a fair amount of effort to add marker gene sets for each cell type and would like to retain these without having to reload them.

Did you get a chance to check out my response in the other issue #2569 that was also opened on the subject, and was that approach sufficient for your use case?

Speaking more generally, I agree that it would be useful to be able to save and share a state for the explorer. That being said,   I think that for the CELL x GENE desktop explorer, being able to share a state is somewhat approximated by functionality that is already available in the application (the application can create and consume both gene sets and custom annotations of select cell populations).

So via the `--gene-sets-file` and `--annotations-file` OR the `--user-generated-data-dir` options, there are workarounds to sharing previous work w.r.t. previously identified cell (sub) populations and sets of marker genes that define particular populations of interest. The solution is not perfect, as someone who is receiving the files that communicate previously generated cell/gene annotations in the explorer will need to find and color by those annotations/genes/gene sets. That being said, since there are alternative mechanisms to save and share the core information (annotated cells + annotated genes/sets) that would be encoded in a deep linking approach, it seems like there is other functionality/value that is not currently served by the application that should be prioritized ahead of this particular feature. Always curious to hear about how the proposed solution does not meet anybody's particular requirements, though!

Now, to take this thread on the scenic route...

For users who have more of a 'publication use case', I think it would be very cool to enable the user to construct something like a sequence of application states to be able to tell a story about datasets (as a crude example, someone could create a sequence of states that walk a viewer through exploring initial QC metrics, then walk through markers of the broader cell type populations, and subsequently through markers of fine cell type populations). In short, I think the ability to sequence these application states might enable users to walk dataset viewers through the logic/story that is outlined in their publication, or could simply point out the highlights of the dataset before giving the viewer the ability to do more custom explorations (potentially based off the framework that the original user/publisher has defined). This has not been requested by anybody to my knowledge, but wanted to throw in this opinion as a user of the application.
