### ISSUE TITLE
"remove" on gene histogram is ambigious

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#667]
When selecting a range of gene expression values and the user wants to clear selection, it's not clear how to do this. User may click "remove" expecting it to remove the selection, but it removes the gene histogram.

(note: undo/redo may ease this pain point, since the user can recover the gene histogram)

**Comment by bkmartinjr** [comment]
Assigning to @liaprins-czi, to see if there are design suggestions which would address this.

**Comment by liaprins-czi** [comment]
This relates to how we might want to reorganize/reformat the histograms overall; I have collected my explorations and recommendations in this file. The explorations include alternative ways for the user to remove a histogram rather than the current "remove" button.
https://docs.google.com/document/d/1K-CmvAC9NtoFbngInE4WJ2jdHvw8mZdm9Lr0nmov4tU/edit#heading=h.p3jkq0ferl9b

**Comment by signechambers1** [comment]
This is a problem but closing as it is a low priority for 2021
