### ISSUE TITLE
Add CLI argument to `launch` for switching between `.X` and `.raw`

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#689]
Thanks so much to @gokceneraslan (#676) and @Marius1311 (#542) for flagging the related issues of how to visualize `.raw` versus `.X` (and making it clear which one you're looking at!). 

Making a new issue to offer a proposed solution for discussion.

It's rather confusing and/or misleading to visualize normalized and unnormalized values in the same view. One solution would be to toggle back and forth between viewing `.raw` and `.X` within the app (as suggested by @gokceneraslan :). 

However, the frontend currently only accommodates a single matrix of values. Under the hood, toggling would be effectively the same as relaunching. 

I'd propose to just add a command line argument to `launch` that allows the user to specify whether they want to load the raw count values from `.raw` or the normalized values from `.X` (the default). 

Would this adequately solve the needs presented in #676 and #542? All feedback and thoughts welcome!

**Comment by Marius1311** [comment]
Dear @sidneymbell , that sounds good to me!

**Comment by gokceneraslan** [comment]
Sounds good to me, too. Ideally, the gene search should always be performed in `.raw` since gene subsetting in Scanpy (i.e. `ad = ad[:, somegenes]` or sc.pp.filter_genes) filters out genes in `X` but always keep all genes in `raw.X`. But if it's challenging technically, specifying from the command line is also ok.

What about the layers? I think it also makes sense to select a layer from the command line. What do you think?

**Comment by alokito** [comment]
Anecdotally some users say toggling between raw and normalized values would be ideal, and that Seurat recommends performing differential expression analysis on the raw values.

**Comment by signechambers1** [comment]
Fixed via #1030
