### ISSUE TITLE
cluster occupancy is missing values

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#721]
cluster occupancy is missing values. 1M+ cells, so maybe something is off with the binning?

![image](https://user-images.githubusercontent.com/1245615/56465879-c0228500-63bc-11e9-89a9-64838a89ae51.png)

**Comment by neuromusic** [comment]
same problem on tabula muris:

![image](https://user-images.githubusercontent.com/1245615/56835156-4e1cc680-6828-11e9-9a15-8dbe64907735.png)

to reproduce:

1. open tabula muris
2. color by barcode
3. expand mouse.id

**Comment by bkmartinjr** [comment]
@neuromusic - can you confirm that this *only* happens when you color-by plate.barcode (for TM_facs test data)?

Also, on the other dataset, can you open the "cluster_label" category, and tell me if it has a "truncated list" text label at the very end of the category checklist?  

If so, this is caused by columns which contain a very large number of items.  We truncate the list (by default, to 100), and this affects the summary calculation.   

Just want to confirm that I'm chasing your actual test case.

**Comment by neuromusic** [comment]
> can you confirm that this only happens when you color-by plate.barcode (for TM_facs test data)?

confirmed

> Also, on the other dataset, can you open the "cluster_label" category, and tell me if it has a "truncated list" text label at the very end of the category checklist?

yep!

**Comment by neuromusic** [comment]
Based on my explorations in #737, it seems like the truncated cells still have colors assigned to them, even though they don't show up in the list of labels. If that is right, can we construct the cluster occupancies to include these truncated values?

**Comment by bkmartinjr** [comment]
Root cause - the occupancy component was using the top N truncated category value list to create occupancy stacks, rather than the full set of category values.
