### ISSUE TITLE
Condense toolbar

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#736]
![image](https://user-images.githubusercontent.com/1770265/56929872-b91c0680-6a8f-11e9-8aba-ca0074163d88.png)

Each icon and action we add to the top right creates incrementally more pressure to condense the toolbar into a menu, or a series of icons along the top, or both.

**Comment by liaprins-czi** [comment]
Linking to some Figmas with my explorations for this:
https://www.figma.com/file/jUuBp8j5DWN4Lvj1GQ7byn/Scroll-under-top-bar?node-id=2%3A78
and
https://www.figma.com/file/Cs4p5xuos4T4dXR87ftOuN/Histogram-explorations?node-id=64%3A0 (need to go to p3 and scroll over to vertical column of screens on right side).

**Comment by liaprins-czi** [comment]
Proposal for new top bar design:
![topbar-proposal-1.png](https://images.zenhubusercontent.com/5d4c6939b2c9257cd301cec2/aac31e43-8235-4bac-8fce-7a3abe7e43ad)

- Remove drop shadow from left sidebar
- Add 1px line to separate left sidebar from main vis (#7F7F7F)
- Put top action bar + cellxgene logo into white rectangle at top, separated from left sidebar and main vis by 1px line below it (#7F7F7F)
- Left sidebar should scroll below topbar (same with main vis)
- I also redesigned the dataset name a bit, and it should be able to fit a much longer name now. I added its file extension (.h5ad), made the type size a bit bigger, and changed to grey type (#7F7F7F). There is also a pipe/line separating the cellxgene logo from the dataset name with more padding between.

If you want more specific specs let me know! I am not sure if px are the best way to specify things since I wasn't sure if WebGL uses px...

**Comment by liaprins-czi** [comment]
![Screen Shot 2019-09-17 at 10 59 07 AM](https://user-images.githubusercontent.com/53277128/65067311-12031300-d93b-11e9-8b96-09f733ab37eb.png)
Specs above, but let me know if you have any questions. Also what size(s) the new "subset" icon needs to be, and I can export it.
