### ISSUE TITLE
Can't load h5ad with "name" obs

### ISSUE THREAD

**Issue by nspies-celsiustx** [chanzuckerberg/cellxgene#779]
It appears that cellxgene chokes when trying to load a dataset containing an obs column called "name". It'd be great if it could at least provide a more meaningful error message and ideally provide compatibility with datasets containing such a column.

```python
import scanpy as sc

import numpy as np
import pandas as pd

# create an AnnData instance with random data
X = np.random.randint(0, 1000, size=(1000, 50))

adata = sc.AnnData(X)
adata.obs = pd.DataFrame({"x":np.random.random(size=(1000,))})
sc.tl.tsne(adata)

adata.write("adata.h5ad")

# now add a column "name"
adata.obs["name"] = ["a", "b"] * 500
adata.write("adata_with_name.h5ad")
```

Running on adata_with_name.h5ad causes the following error:

```
$ cellxgene launch -v --debug -l tsne  adata_with_name.h5ad
[cellxgene] Starting the CLI...
[cellxgene] Loading data from adata_with_name.h5ad.
Traceback (most recent call last):
  File "/mnt/home/nspies/.local/bin/cellxgene", line 11, in <module>
    load_entry_point('cellxgene', 'console_scripts', 'cellxgene')()
  File "/mnt/home/nspies/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/home/nspies/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/mnt/home/nspies/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/home/nspies/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/home/nspies/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/home/nspies/Downloads/cellxgene/server/cli/launch.py", line 185, in launch
    server.attach_data(ScanpyEngine(data, args), title=title)
  File "/mnt/home/nspies/Downloads/cellxgene/server/app/scanpy_engine/scanpy_engine.py", line 35, in __init__
    self._validate_and_initialize()
  File "/mnt/home/nspies/Downloads/cellxgene/server/app/util/utils.py", line 42, in wrapped_function
    return func(self, *args, **kwargs)
  File "/mnt/home/nspies/Downloads/cellxgene/server/app/scanpy_engine/scanpy_engine.py", line 169, in _validate_and_initialize
    self._validate_data_types()
  File "/mnt/home/nspies/Downloads/cellxgene/server/app/util/utils.py", line 42, in wrapped_function
    return func(self, *args, **kwargs)
  File "/mnt/home/nspies/Downloads/cellxgene/server/app/scanpy_engine/scanpy_engine.py", line 234, in _validate_data_types
    datatype = curr_axis[ann].dtype
  File "/usr/local/lib64/python3.7/site-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'dtype'
```
Running `cellxgene launch -l tsne adata.h5ad` works fine.

**Comment by csweaver** [comment]
Hi @nspies-celsiustx, thanks for the detailed bug report. I'll try to replicate the issue and get back to you.

**Comment by bkmartinjr** [comment]
I have reproduced the bug.  In doing so I have found several other areas where we do not correctly handle the diversity of data types that could be in an anndata.

Currently:
* we assume all obs and var column names are unique, but never bother to check
* the front-end is hard-wired to assume that the contents of the `name` column are unique, human-readable names suitable for displaying in the UI (eg, in the gene search box).  The ScanPy back-end adapter currently has some (buggy) logic that creates this column from the dataframe index, unless the user overrides this with `--obs-name` or `--var-name`.   This fails due to the aforementioned issue when there is already a `name` column.

This is a case where making assumptions about the dataset internal naming is bad practice (eg, presuming `name` is available for our own use).   Our only real application requirement is a column containing unique, human-readable names for var and obs.

Proposed change:
- [ ] enforce uniqueness on both `obs` and `var` column names (eg, `adata.obs.columns.is_unique`).  While we might be able to do better in the future, it will be a big change and/or require aliasing of names to uniqueify them.  In real-world use, I'm don't think this will be a signficant restriction.
- [ ] introduce two config values, to be shared between front- and back-end, called `obs-name` and `var-name`.  These are the column names containing the human-readable name for each row/col, eg, gene name.  Parameterize both front- and back-end so we do not assume `name`, but instead use the config value.
- [ ] By default, look to the dataframe indices for the unique, human-readable names (eg, `adata.obs.index`).   Continue to support the preexisting CLI options  `--obs-name` and `--var-name` for the case where the user wishes to specify a different column.
- [ ] enforce that the `obs-name` and `var-name` columns exist and contain unique values

Our over-the-wire dataframe format does not have a magic index name, so in practice the default (using the index) will be implemented by probing for an unused column name, and setting `obs-name` or `var-name` to this dynamically generated name.

@csweaver - please comment before I make the change.

**Comment by nspies-celsiustx** [comment]
Great, thanks for the quick turnaround on this!
