### ISSUE TITLE
--layout CLI param help confusing

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#824]
the help text for `--layout` is confusing - it should clearly state that not specifying a layout will make *all* embeddings in the dataset available, and that specifying layout names will restrict options to those specified.

Changes to be made:
* [x] CLI parameter --layout modified to accept N embedding names (rather than the current restriction of one).  Any specified will present in the web UI.   Default, if not specified, is to present all embeddings.
* [x] CLI parameter --layout changes to --embedding. Help and error text in the CLI change corresponding.
* [x] UI text changes from layout to embedding (eg, in the menu used to select an embedding)

**Comment by liaprins-czi** [comment]
Adding screenshot of current text for reference; will return to this issue soon with suggestions.
<img width="490" alt="Screen Shot 2019-08-09 at 8 44 07 AM" src="https://user-images.githubusercontent.com/53277128/62791889-f75b9580-ba82-11e9-96e5-761487cd025a.png">

**Comment by liaprins-czi** [comment]
Question: Is there a benefit to the user specifying a layout? Are they able to specify one that otherwise would not be available in the UI'd dropdown? If they know they only care about one layout, does that make it faster to launch their instance (and if so, by how approx much)? Is this option available simply to prevent users from needing to use the dropdown, if they do in fact know they only care about one layout view?

**Comment by liaprins-czi** [comment]
Okay, so here is a first pass at new phrasing, assuming we keep the functionality overall the same as we have it now (I have suggestions below for how we might consider changing it in future, though). Also, this text is kinda long, and the terms/semantics might be a bit off, so feel to suggest updates, anyone!

`-l, --layout TEXT`
`If dataset has more than one layout enabled, specify which layout to use (e.g. 'umap'). If no layout choice is specified, all layouts enabled in the dataset will be available as choices in the UI.`

**Here are some other things we might consider:**
- If user _has_ specified a particular layout, then we don't show the "layout choice" button in the UI at all (since it only has the current layout selection listed, which is a little weird and also user can't do anything with it from there anyway).

![Screen Shot 2019-08-12 at 10 39 47 AM](https://user-images.githubusercontent.com/53277128/62886318-dfd51480-bcef-11e9-9a84-1311368b9c4e.png)

- Alternatively, keep the "layout choice" button in the UI, but add more info somehow along the lines of "To have access to all available layout choices here, do _not_ use the `layout` command in the CLI to specify a particular layout." (Although we might not want to show this if the user had in fact _not_ specified a layout in CLI, and the dataset simply enabled just one layout type...not sure if we'd be able to draw that distinction easily?)

- Even better from a user experience perspective (at least in my humble opinion, without knowing nearly as much about our users right now as the rest of you, so I may be off-base): Let user specify the _default_ layout choice that appears upon launch, but keep all enabled layout choices available via radio buttons in the UI dropdown. This way user does not need to re-run launch in case they decide they want to see a different layout's perspective. (If we change it to this way, we'd need slightly different help text than what I wrote above.) **Question: Would there be any harm to doing this idea? Would it be difficult to implement?**

**Comment by liaprins-czi** [comment]
@sidneymbell Do you have input or ideas for what would be better for the `--layout` option?

- keep current functionality (specifying a layout via CLI means _no other_ layouts are available in the UI)
or 
- change functionality so that specifying a layout via CLI means that the specified layout is _default_ when they open cellxgene, but they still have access to switching to any of the other available layouts through the UI's "Layout choice" radio buttons

**Comment by sidneymbell** [comment]
I actually think this is outdated; now that we support *any* layout
specified in `adata.obsm['X_foo']`, we could probably even just remove this
argument. If we keep it, I'd be in favor of the changed functionality you
propose where it specifies a default instead.

**Comment by bkmartinjr** [comment]
the nominal reason we kept the CLI param (ie, ability to restrict to a single embedding viz) was for performance on large data sets.  I'm not sure in practice how much it matters.

**Comment by sidneymbell** [comment]
Is the difference in load time more than a few seconds? I think it's worth
a few seconds to have all the layouts available.

**Comment by sidneymbell** [comment]
Thanks for the context! Hmm. For typical use, I'd favor changing the
default behavior to load all layouts by default. Once they're loaded, we
shouldn't see any downstream perf hits, correct?

**Comment by liaprins-czi** [comment]
I think the idea we discussed in this week's standup made so much sense:

**Allow the user to specify multiple layouts.**

This way they can still switch between multiple in the UI, but only those that they specified. If they have several possible layouts in their dataset, and it is a large file, this can prevent cxg from loading all of them, instead just the one(s) the user specifies to see. 

The UI's list of radio buttons for each layout choice should probably be in the order that the user lists via the `--layout` parameter, with the first listed being the default view.

I am thinking that the way they'd specify multiple would be:
`--layout umap tsne pca`
or
`-l umap tsne pca`

Now for the help text for `-l, --layout` in the CLI, which was the original point of this GH issue; here's what I'm thinking:

`-l, --layout TEXT`
`If dataset has more than one layout enabled, specify which layout(s) to use (e.g. 'umap'). To use more than one layout, separate with a space (e.g. 'umap tsne'). If no layout choice is specified, all layouts enabled in the dataset will be available as choices in the UI.`

**Comment by sidneymbell** [comment]
This is a great proposal, thanks Lia!!

One nit: "layout" is mostly internal language :). I'd suggest "embedding"
instead. That said, I think people can easily figure out what we mean by
"layout," and there are some edge cases where "embedding" isn't quite
right, either (e.g. spatial coordinates).

**Comment by bkmartinjr** [comment]
@sidneymbell - are you proposing s/layout/embedding/ in the CLI param/help/etc, or also in the web UI (eg, "Select layout" is current text in drop-down).

I assume everywhere that has an end-user UI?

**Comment by sidneymbell** [comment]
That would be my suggestion. That said, I don't think it's of
utmost importance.

**Comment by bkmartinjr** [comment]
Lets just clean it all up in one shot.   @liaprins-czi - I'll start a list of changes in this issue.  If you could add to it, I would appreciate it.
