### ISSUE TITLE
continuous data visualization on the top of the categorical data

### ISSUE THREAD

**Issue by aopisco** [chanzuckerberg/cellxgene#829]
add a toggle to remove the zeros when showing the histogram;

after removing the zeros we can recompute the distributions and make the y-axis relative to the total number of non-zero cells for a particular gene

that will allow is to compare the mean expression and distributions across the different groups

**Comment by sidneymbell** [comment]
I would totally love this! If I knew how the incoming data was preprocessed, we would totally do this. But, it's tricky because datasets come in with such a wide array of preprocessing (e.g., in some cases, `0` is actually the median of the data). There are some heuristics we could use to say "if it's the min value, drop it", but this seems pretty brittle, unfortunately.
