### ISSUE TITLE
Better handle long dataset titles

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#871]
See #858, which cuts off the title if it's too long (less than ideal) to prevent overflow onto new line, or out of sidebar area. 

Currently, the full title is available on hover. 

The quickest thing to do is probably to leave things as they are now, but make it more obvious the title is cut off.

**Comment by liaprins-czi** [comment]
@colinmegill Is it possible to do ellipses in the middle of the file name (preserving the first and last portions of the name + file extension)? E.g. how Finder does it (see screen shot below). This would be a good way I feel, since some ppl add version numbers/indicators at the end of the file name, and some at the beginning. This method preserves most of the parts of the file name that are likely to provide helpful context, I feel.

![Screen Shot 2019-08-06 at 9 19 51 AM](https://user-images.githubusercontent.com/53277128/62557354-ad2ca700-b82b-11e9-8c3b-ae4102f72f1f.png)

Here are a few links I found from a quick search, which may or may not provide some clues as to feasibility:

- https://codepen.io/markchitty/pen/RNZbRE
- https://stackoverflow.com/questions/8403086/long-path-with-ellipsis-in-the-middle

**Comment by colinmegill** [comment]
Fantastic idea, yes, we can do that!

**Comment by liaprins-czi** [comment]
@colinmegill Should I assign this one back to you now?

**Comment by colinmegill** [comment]
Seve!

**Comment by seve** [comment]
@liaprins-czi @colinmegill @bkmartinjr , I'm on it!
