### ISSUE TITLE
Option to load anndata in backed mode

### ISSUE THREAD

**Issue by joshua-gould** [chanzuckerberg/cellxgene#914]
Use case: I have a large anndata h5ad file, that I want to open in cellxgene to view the expression of genes of interest on a 2d embedding, but am unable to do so because cellxgene loads the entire matrix into memory

**Comment by bkmartinjr** [comment]
See discussion in #739 on problems with backed mode and anndata.

I'm working on a benchmark and will file issues with anndata

**Comment by bkmartinjr** [comment]
Preliminary benchmarking shows same result as on past version of anndata.  Backed mode (eg, `backed='r'`) has the following effect:
* load time improves (anywhere from 1.5 to 40X faster on my test data sets)
* slicing of data from the expression matrix (`X`) is substantially slower (2-20X slower)

More importantly, the user "wait" time for lazy loading expression (`anndata.X`) goes from ms to seconds, putting it directly into the realm of negatively affecting UI.

@joshua-gould - one option is we add a CLI parameter to load in backed mode, if you value init-time speedup over access to expression data.   Could you comment on this trade-off for your use case?

CC: @liaprins-czi

**Comment by joshua-gould** [comment]
I value less memory usage. My dataset is too large to be loaded into memory
on my computer. Loading genes as needed solves my issue. I'm willing to
trade slower access for less memory. Thanks.

**Comment by bkmartinjr** [comment]
makes sense.  I am imagining this as a (default off) option, from the CLI, intended for more advanced users.    Let me know if you had another idea.

I will try to get this into our next release.

**Comment by bkmartinjr** [comment]
@joshua-gould I have a draft PR available if you want to have a look.  TL;DR - it adds a new `--backed` flag that causes the app to load with `backed="r"`.   Appreciate it if you could try that branch on your dataset, or give me a pointer to your data so I can test it prior to ship.

Caveats:
* if you access adata.X (eg, load a gene or perform differential expression), it will be slower than the in-mem version.
* performance of anndata backed mode for sparse data is slow, due to some regressions (it will read the entire X array if you access any given column).  This issue is known to the ScanPy team, and @ivirshup has an open [PR](theislab/anndata#227) that is addressing the underlying issues.    When that lands, I suspect performance on sparse CSC backed data will get a lot better. 

I'm still sorting through the performance issues and looking for work-arounds.  So this may change a bit over the next week.   I also plan to test this a bit more and include in our imminent release.   Any help on the above test/validation would be appreciated.

**Comment by joshua-gould** [comment]
Looks good, thanks

**Comment by bkmartinjr** [comment]
Hi @joshua-gould - would appreciate feedback on the `--backed` support in the latest release (on PyPi).  Let me know how it works for you...

**Comment by joshua-gould** [comment]
Works great so far. Thanks.
