### ISSUE TITLE
When zoom in, the dots don’t scale to be perfect circles

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#960]
Ideally they'd be perfectly round and smooth-edged circles at all zoom levels. 

Current state:
<img width="319" alt="dots not perfect circles_not aliasing well" src="https://user-images.githubusercontent.com/53277128/65995914-43a3d000-e44b-11e9-94a4-7bec717ca99f.png">

Link from Colin:
https://www.desultoryquest.com/blog/drawing-anti-aliased-circular-points-using-opengl-slash-webgl/

**Comment by bkmartinjr** [comment]
This is an intentional performance improvement in our rendering.  The anti-aliasing approach consumes significantly more GPU cycles.   That said, I can implement it if you want to see a demonstration (I had done it once before, and thought it was onerous - but I did not fully quantify that impression).

**Comment by liaprins-czi** [comment]
I do not need a demo of it; thanks for explaining this tradeoff. I agree it would not be worth the perfomance hit to get slightly more circular circles in return.

**Comment by bkmartinjr** [comment]
closing as we have decided to not fix.

**Comment by colinmegill** [comment]
Linking to #875 as we may want a slower, more perfect rendering model for publication and screenshot use cases down the road.
