### ISSUE TITLE
Continuous selection tool: quantify selected cells

### ISSUE THREAD

**Issue by grst** [chanzuckerberg/cellxgene#990]
Hi, 

I believe it would be useful if the continuous selection-tool could display a metric on the fraction of cells currently selected. 

Here's a mock image to show what I mean: 
![2019-10-19_15:48:53_473x479](https://user-images.githubusercontent.com/7051479/67146119-fc5d7200-f287-11e9-8fac-d00022724a2b.png)

Ideally, this could be extended to get the fraction of cells that are selected in *both* the *PDCD1* and *CXCL13* selectors, such as: 

> **2433/54323 cells selected (p-value < 0.0001, Chi-Square-test)**

But I understand that the latter feature might be too specific to my (or rather my customer's) use-case.

**Comment by colinmegill** [comment]
Thanks so much for this, @grst. Your latter suggestion is related to https://github.com/chanzuckerberg/cellxgene/issues/652 #652. 

The former suggestion is a concept we've considered in the context of categorical, ie., all selections should be reflected as `123/9876` cells selected, instead of showing total counts. Subsetting actually renders this information... so the behavior is a bit inconsistent / surprising. 

![image](https://user-images.githubusercontent.com/1770265/67217584-cf20d900-f3d9-11e9-8ab7-4a49ec958bb5.png)
![image](https://user-images.githubusercontent.com/1770265/67218320-09d74100-f3db-11e9-802f-dff6b3d8245e.png)

A major limitation is performance, we cannot do it in real time during interactions, but can probably handle doing it on interaction `end`.

**Comment by signechambers1** [comment]
Closing as a low priority for development in 2021. If we receive more user feedback asking for this functionality we may reconsider!
