### ISSUE TITLE
Autosuggest ontology terms for user-created annotations

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#996]
Great idea from @aopisco: 

When a user is creating a new categorical annotation, allow them to indicate if it's a cell type label. If so, autosuggest terms from the [cell ontology](http://www.obofoundry.org/ontology/cl.html) to standardize vocabulary. This will be important for enabling reuse of these annotations (e.g., for training classifiers later on).

**Comment by bkmartinjr** [comment]
A related use case we should consider is where the user is labeling for purposes other than cell typing (ie, perhaps data QC or a group ad hoc analysis workflow).  In these cases, the user may want their own labeling hierarchy auto-suggested.   Could we generalize this to the idea of a) a configurable auto-suggest taxonomy, b) enforced or not enforced?

**Comment by aopisco** [comment]
@bkmartinjr just for clarification, do you mean for example low read, doublets,...?

**Comment by bkmartinjr** [comment]
yes, that is a great example.   I've seen lots of other ad hoc annotations added to H5ADs suggesting that there are group workflows using labeling, and which might benefit from label consistency

**Comment by sidneymbell** [comment]
Initial backend spec (for iteration):

### CLI:
_@liaprins-czi feel free to make suggestions / edits to this strawman :)_

`--annotations-ontology <filepath>`
Help text:
```
When creating annotations, optionally autocomplete names from ontology terms [default: off]. 

Pass an .obo file to specify a custom ontology; otherwise, defaults to the Cell Ontology from http://www.obofoundry.org/ontology/cl.html
```


Backend (flat string MVP):
[See this notebook](https://github.com/chanzuckerberg/cellxgene-vignettes/blob/master/method-testing/ontologies-parsing.ipynb)

**Comment by liaprins-czi** [comment]
Here is a doc of the guidelines @sidneymbell and I have been thinking for this work:
https://drive.google.com/open?id=1-7zeBmMzjfZA0bSZVv2-D_AWbvvVEuorsID65-2UFGw

Here is a link to the Figma with explorations:
https://www.figma.com/file/j0OrP1bd1LQbZOWPbKSMlI/Annotations-ontologies?node-id=40%3A0

Here are some Blueprint components which might be helpful for surfacing hierarchy within the ontology suggestions:
- [Tree](https://blueprintjs.com/docs/#core/components/tree)
- [Breadcrumbs](https://blueprintjs.com/docs/#core/components/breadcrumbs)
- [Overflow list](https://blueprintjs.com/docs/#core/components/overflow-list)
- [Divider](https://blueprintjs.com/docs/#core/components/divider)

**Comment by bkmartinjr** [comment]
@sidneymbell - as I understand your CLI argument structure (above), you want two modes:
* `cellxgene launch foo.h5ad --annotations-ontology` -- use the default cl.obo
* `cellxgene launch foo.h5ad --annotations-ontology myterms.obo` -- just a user-specified obo file.

The problem with this is that variable-parameter count CLI params are extremely user-unfriendly.  Consider what happens if they reorder the CLI params (otherwise completely legal):

`cellxgene launch --annotations-ontology foo.h5ad` 

This will try to use the `foo.h5ad` as the obo file and presumably fail. We could add heuristics (eg, consume only if an obo file), but that kind of magic is even more inscrutable.

Typical UX guidelines discourage variable-count params for this reason (ie so the behavior is independent of where it exists in the command line string).

If OK with you, I will initially implement without the defaulting.  If we need the default, I see two options (you may have better ideas!):
* a separate param, eg, `--annotations-ontology-use-default-terms`
* a magic name, eg, `--annotatoins-ongology -`


I am also going to prefix with `--experimental` until we decide this is a supported feature.
